=== abgox/PSCompletions/schema/completion-manifest.en-US.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "required": [
    "meta"
  ],
  "definitions": {
    "string": {
      "type": "string",
      "minLength": 1
    },
    "array": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "array-items-string": {
      "$ref": "#/definitions/array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "name": {
      "title": "Command name",
      "markdownDescription": "It should be a full name, and the short name should be in `alias`",
      "examples": [
        ""
      ],
      "allOf": [
        {
          "$ref": "#/definitions/string"
        },
        {
          "if": {
            "pattern": " "
          },
          "then": {
            "pattern": "(^\".+\"$)|(^'.+'$)",
            "errorMessage": "If spaces are needed, please use \" or ' to wrap them, for example: 'hello world'"
          }
        }
      ]
    },
    "alias": {
      "title": "Command alias",
      "markdownDescription": "It should be a short name, and the full name should be in `name`",
      "examples": [
        []
      ],
      "allOf": [
        {
          "$ref": "#/definitions/array-items-string"
        },
        {
          "items": {
            "if": {
              "pattern": " "
            },
            "then": {
              "pattern": "(^\".+\"$)|(^'.+'$)",
              "errorMessage": "If spaces are needed, please use \" or ' to wrap them, for example: 'hello world'"
            }
          }
        }
      ]
    },
    "tip": {
      "markdownDescription": "Completion item tip `ToolTip`\n- General structure of the completion tip: `Usage` + `Description` + `Example`\n- Here is an example:\n```json\n  \"tip\": [\n    \"U: -r, --revisions <REVSETS>\",\n    \"xxx (Here is the description)\",\n    \"E: -r '@-'   --- xxx (Example description)\"\n    \"   -r 'x-'   --- xxx (Example description)\"\n  ]\n  ```",
      "examples": [
        []
      ],
      "allOf": [
        {
          "$ref": "#/definitions/array-items-string"
        },
        {
          "not": {
            "contains": {
              "pattern": "[\\r\\n]"
            }
          },
          "errorMessage": "Each item in the array will automatically add a line break at the end when displayed, so line breaks are not allowed."
        },
        {
          "items": {
            "not": {
              "pattern": "[\\u4e00-\\u9fff][A-Za-z]|[A-Za-z][\\u4e00-\\u9fff]"
            },
            "errorMessage": "Chinese and English must be separated by a space"
          }
        }
      ]
    },
    "repeat": {
      "type": "number",
      "description": "Maximum number of times this item can repeat.",
      "minimum": 1,
      "examples": [
        1,
        2,
        3,
        4,
        5,
        99
      ]
    },
    "item": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "$ref": "#/definitions/name"
        },
        "alias": {
          "$ref": "#/definitions/alias"
        },
        "tip": {
          "$ref": "#/definitions/tip"
        },
        "repeat": {
          "$ref": "#/definitions/repeat"
        },
        "next": {
          "$ref": "#/definitions/next"
        },
        "option": {
          "$ref": "#/definitions/option"
        }
      },
      "additionalProperties": false
    },
    "next-item": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "$ref": "#/definitions/name"
        },
        "alias": {
          "$ref": "#/definitions/alias"
        },
        "tip": {
          "$ref": "#/definitions/tip"
        },
        "next": {
          "$ref": "#/definitions/next"
        },
        "option": {
          "$ref": "#/definitions/option"
        }
      },
      "additionalProperties": false
    },
    "next": {
      "markdownDescription": "Next subcommand completion\n- It can be an array or the number `0`\n- If it is an array\n  - Items in the array are automatically added to the completions.\n  - If there are `hooks`, they will be added dynamically.\n- If it is the number `0`\n  - It indicates that a content should be input at this time.\n  - However, [PSCompletions](https://pscompletions.abgox.com) is unable to provide completions, and users need to input manually.\n  - `0` tells [PSCompletions](https://pscompletions.abgox.com) that it should display symbols of the `WriteSpaceTab` type to achieve symbol prediction.",
      "type": [
        "array",
        "number"
      ],
      "examples": [
        [],
        0
      ],
      "uniqueItems": true,
      "items": {
        "$ref": "#/definitions/next-item"
      },
      "if": {
        "type": "number",
        "not": {
          "const": 0
        }
      },
      "then": {
        "not": true,
        "errorMessage": "It must be an array or the number 0"
      }
    },
    "option": {
      "type": "array",
      "uniqueItems": true,
      "markdownDescription": "Next optional completion\n - Usually starts with `-` or `--`\n - For example, `--list`",
      "items": {
        "$ref": "#/definitions/item"
      }
    }
  },
  "properties": {
    "meta": {
      "type": "object",
      "description": "Additional information for the completion command",
      "required": [
        "url",
        "description"
      ],
      "properties": {
        "url": {
          "description": "Homepage or repository address of the completion command",
          "allOf": [
            {
              "$ref": "#/definitions/string"
            },
            {
              "pattern": "^https?://",
              "errorMessage": "It must be a valid http/https URL"
            }
          ]
        },
        "description": {
          "description": "Description of the completion command",
          "allOf": [
            {
              "$ref": "#/definitions/array-items-string"
            },
            {
              "not": {
                "contains": {
                  "pattern": "\\n"
                }
              },
              "errorMessage": "Each item in the array will automatically add a line break at the end when displayed, so line breaks are not allowed."
            },
            {
              "items": {
                "not": {
                  "pattern": "[\\u4e00-\\u9fff][A-Za-z]|[A-Za-z][\\u4e00-\\u9fff]"
                },
                "errorMessage": "Chinese and English must be separated by a space"
              }
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "next": {
      "description": "Subcommand completion for the root command",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/next-item"
      }
    },
    "option": {
      "markdownDescription": "Optional completion for the root command",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/item"
      }
    },
    "global_option": {
      "markdownDescription": "Global optional completion\n- Any time you trigger completion, they will be displayed\n- Unless you have used it or its alias",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/item"
      }
    },
    "config": {
      "description": "Special configuration items for the completion command",
      "$ref": "#/definitions/array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "value",
          "tip"
        ],
        "properties": {
          "name": {
            "description": "Name of the special configuration item",
            "$ref": "#/definitions/string"
          },
          "value": {
            "description": "Default value of the special configuration item",
            "type": [
              "string",
              "number"
            ]
          },
          "values": {
            "markdownDescription": "Optional values of the special configuration item\n- Here, you can fill in the values that will be displayed when the command completion is triggered\n - Suppose the command completion is `xxx` and the configuration item name is `enable_xxx`\n - Then, when you input `psc completion xxx enable_xxx` and trigger completion, the values in the `values` array will be displayed in the completion list",
            "$ref": "#/definitions/array",
            "items": {
              "type": [
                "string",
                "number"
              ]
            }
          },
          "tip": {
            "description": "Tip information for the special configuration item",
            "$ref": "#/definitions/array-items-string"
          }
        }
      }
    },
    "info": {
      "markdownDescription": "Additional information\n- They can be accessed in the `tip` field of this json file using `{{ $info.xxx }}`\n- If you need to add line breaks, please use `\\n`",
      "type": "object",
      "minProperties": 1
    }
  },
  "additionalProperties": false
}

=== abgox/PSCompletions/completions/tombi/language/zh-CN.json
{
  "meta": {
    "url": "https://tombi-toml.github.io/tombi/",
    "description": [
      "TOML 工具包"
    ]
  },
  "next": [
    {
      "name": "completion",
      "tip": [
        "U: completion <SHELL>",
        "生成 shell 自动补全脚本"
      ],
      "next": [
        {
          "name": "bash",
          "tip": [
            "生成 bash 自动补全脚本"
          ]
        },
        {
          "name": "elvish",
          "tip": [
            "生成 elvish 自动补全脚本"
          ]
        },
        {
          "name": "fish",
          "tip": [
            "生成 fish 自动补全脚本"
          ]
        },
        {
          "name": "powershell",
          "tip": [
            "生成 powershell 自动补全脚本"
          ]
        },
        {
          "name": "zsh",
          "tip": [
            "生成 zsh 自动补全脚本"
          ]
        }
      ]
    },
    {
      "name": "format",
      "tip": [
        "格式化 TOML 文件"
      ],
      "option": [
        {
          "name": "--check",
          "tip": [
            "仅检查，不覆盖文件"
          ]
        },
        {
          "name": "--diff",
          "tip": [
            "显示格式化变更"
          ]
        },
        {
          "name": "--no-cache",
          "tip": [
            "不使用缓存"
          ]
        },
        {
          "name": "--offline",
          "tip": [
            "禁用网络访问"
          ]
        },
        {
          "name": "--quiet",
          "tip": [
            "静默模式"
          ]
        },
        {
          "name": "--stdin-filename",
          "tip": [
            "U: --stdin-filename <STDIN_FILENAME>",
            "从 stdin 读取时使用的文件名"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "lint",
      "tip": [
        "检查 TOML 文件"
      ],
      "option": [
        {
          "name": "--error-on-warnings",
          "tip": [
            "遇到警告时退出并返回错误码"
          ]
        },
        {
          "name": "--no-cache",
          "tip": [
            "不使用缓存"
          ]
        },
        {
          "name": "--offline",
          "tip": [
            "禁用网络访问"
          ]
        },
        {
          "name": "--quiet",
          "tip": [
            "静默模式"
          ]
        },
        {
          "name": "--stdin-filename",
          "tip": [
            "U: --stdin-filename <STDIN_FILENAME>",
            "从 stdin 读取时使用的文件名"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "lsp",
      "tip": [
        "运行 TOML 语言服务器"
      ],
      "option": [
        {
          "name": "--no-cache",
          "tip": [
            "不使用缓存"
          ]
        },
        {
          "name": "--offline",
          "tip": [
            "禁用网络访问"
          ]
        }
      ]
    }
  ],
  "option": [
    {
      "name": "--verbose",
      "alias": [
        "-v"
      ],
      "tip": [
        "更改日志级别",
        "-v: DEBUG, -vv: TRACE"
      ],
      "repeat": 2
    },
    {
      "name": "--version",
      "alias": [
        "-V"
      ],
      "tip": [
        "U: -V, --version",
        "打印版本信息"
      ]
    }
  ],
  "global_option": [
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "打印帮助信息"
      ]
    }
  ]
}

=== abgox/PSCompletions/completions/glow/language/zh-CN.json
{
  "meta": {
    "url": "https://github.com/charmbracelet/glow",
    "description": [
      "在终端中渲染 Markdown 文件！"
    ]
  },
  "next": [
    {
      "name": "completion",
      "alias": [
        "c"
      ],
      "tip": [
        "U: completion [COMMAND]",
        "生成指定 shell 的自动补全脚本"
      ],
      "next": [
        {
          "name": "bash",
          "tip": [
            "生成 bash 的自动补全脚本"
          ],
          "option": [
            {
              "name": "--no-descriptions",
              "tip": [
                "禁用补全描述"
              ]
            }
          ]
        },
        {
          "name": "fish",
          "tip": [
            "生成 fish 的自动补全脚本"
          ],
          "option": [
            {
              "name": "--no-descriptions",
              "tip": [
                "禁用补全描述"
              ]
            }
          ]
        },
        {
          "name": "powershell",
          "tip": [
            "生成 powershell 的自动补全脚本"
          ],
          "option": [
            {
              "name": "--no-descriptions",
              "tip": [
                "禁用补全描述"
              ]
            }
          ]
        },
        {
          "name": "zsh",
          "tip": [
            "生成 zsh 的自动补全脚本"
          ],
          "option": [
            {
              "name": "--no-descriptions",
              "tip": [
                "禁用补全描述"
              ]
            }
          ]
        }
      ]
    },
    {
      "name": "config",
      "tip": [
        "U: config",
        "编辑 glow 配置文件"
      ],
      "option": [
        {
          "name": "--config",
          "tip": [
            "U: --config <FILE>",
            "配置文件 (默认 C:\\Users\\{{ $env:UserName }}\\AppData\\Local\\glow\\Config\\glow.yml)"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "help",
      "alias": [
        "h"
      ],
      "tip": [
        "U: help [COMMAND]",
        "帮助信息"
      ],
      "next": 0
    }
  ],
  "option": [
    {
      "name": "--all",
      "alias": [
        "-a"
      ],
      "tip": [
        "显示系统文件和目录 (仅 TUI 模式)"
      ]
    },
    {
      "name": "--line-numbers",
      "alias": [
        "-l"
      ],
      "tip": [
        "显示行号 (仅 TUI 模式)"
      ]
    },
    {
      "name": "--pager",
      "alias": [
        "-p"
      ],
      "tip": [
        "使用分页器显示"
      ]
    },
    {
      "name": "--preserve-new-lines",
      "alias": [
        "-n"
      ],
      "tip": [
        "保留输出中的换行符"
      ]
    },
    {
      "name": "--style",
      "alias": [
        "-s"
      ],
      "tip": [
        "U: -s, --style <STYLE>",
        "样式名称或 JSON 路径 (默认 \"auto\")"
      ],
      "next": 0
    },
    {
      "name": "--tui",
      "alias": [
        "-t"
      ],
      "tip": [
        "使用 TUI 显示"
      ]
    },
    {
      "name": "--version",
      "alias": [
        "-v"
      ],
      "tip": [
        "U: -v, --version",
        "显示版本信息"
      ]
    },
    {
      "name": "--width",
      "alias": [
        "-w"
      ],
      "tip": [
        "U: -w, --width <WIDTH>",
        "自动换行宽度 (设置为 0 禁用)"
      ],
      "next": 0
    }
  ],
  "global_option": [
    {
      "name": "--config",
      "tip": [
        "U: --config <FILE>",
        "配置文件 (默认 C:\\Users\\{{ $env:UserName }}\\AppData\\Local\\glow\\Config\\glow.yml)"
      ],
      "next": 0
    },
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "显示帮助信息"
      ]
    }
  ]
}

=== abgox/PSCompletions/completions/vhs/language/zh-CN.json
{
  "meta": {
    "url": "https://github.com/charmbracelet/vhs",
    "description": [
      "你的 CLI 家庭录像机",
      "从 Shell 脚本录制终端 GIF"
    ]
  },
  "next": [
    {
      "name": "new",
      "tip": [
        "U: new <NAME>",
        "创建一个新的 tape 文件，包含示例内容和文档"
      ]
    },
    {
      "name": "publish",
      "tip": [
        "U: publish <GIF>",
        "将 GIF 发布到 vhs.charm.sh 并获取可分享的 URL"
      ]
    },
    {
      "name": "record",
      "tip": [
        "U: record [OPTIONS]",
        "通过录制你的操作创建新的 tape 文件"
      ],
      "option": [
        {
          "name": "--shell",
          "alias": [
            "-s"
          ],
          "tip": [
            "U: -s, --shell <SHELL>",
            "用于录制的 Shell"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "serve",
      "tip": [
        "U: serve",
        "启动 VHS SSH 服务器"
      ]
    },
    {
      "name": "themes",
      "tip": [
        "U: themes",
        "列出所有可用的主题，每行一个"
      ]
    },
    {
      "name": "validate",
      "tip": [
        "U: validate <FILE>...",
        "验证 glob 文件路径并解析所有文件以确保有效，但不运行"
      ]
    }
  ],
  "option": [
    {
      "name": "--output",
      "alias": [
        "-o"
      ],
      "tip": [
        "U: -o, --output <FILE>",
        "视频输出的文件名"
      ],
      "repeat": 99
    },
    {
      "name": "--publish",
      "alias": [
        "-p"
      ],
      "tip": [
        "U: -p, --publish",
        "将 GIF 发布到 vhs.charm.sh 并获取可分享的 URL"
      ]
    },
    {
      "name": "--quiet",
      "alias": [
        "-q"
      ],
      "tip": [
        "U: -q, --quiet",
        "静默模式，不输出日志消息"
      ]
    },
    {
      "name": "--version",
      "alias": [
        "-v"
      ],
      "tip": [
        "U: -v, --version",
        "打印版本"
      ]
    }
  ],
  "global_option": [
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "显示帮助"
      ]
    }
  ]
}

=== abgox/PSCompletions/completions/carapace/language/en-US.json
{
  "meta": {
    "url": "https://carapace.sh/",
    "description": [
      "A multi-shell completion binary"
    ]
  },
  "next": [
    {
      "name": "_carapace",
      "tip": [
        "U: _carapace <SHELL>",
        "Generate completion script for the specified shell"
      ],
      "next": [
        {
          "name": "bash",
          "tip": [
            "Generate bash completion"
          ]
        },
        {
          "name": "bash-ble",
          "tip": [
            "Generate bash-ble completion"
          ]
        },
        {
          "name": "cmd-clink",
          "tip": [
            "Generate cmd-clink completion"
          ]
        },
        {
          "name": "elvish",
          "tip": [
            "Generate elvish completion"
          ]
        },
        {
          "name": "export",
          "tip": [
            "Generate export completion"
          ]
        },
        {
          "name": "fish",
          "tip": [
            "Generate fish completion"
          ]
        },
        {
          "name": "ion",
          "tip": [
            "Generate ion completion"
          ]
        },
        {
          "name": "nushell",
          "tip": [
            "Generate nushell completion"
          ]
        },
        {
          "name": "oil",
          "tip": [
            "Generate oil completion"
          ]
        },
        {
          "name": "powershell",
          "tip": [
            "Generate powershell completion"
          ]
        },
        {
          "name": "tcsh",
          "tip": [
            "Generate tcsh completion"
          ]
        },
        {
          "name": "xonsh",
          "tip": [
            "Generate xonsh completion"
          ]
        },
        {
          "name": "zsh",
          "tip": [
            "Generate zsh completion"
          ]
        }
      ]
    },
    {
      "name": "selfupdate",
      "tip": [
        "U: selfupdate [SOURCE] [TAG] [ASSET]",
        "Update to nightly/stable releases"
      ],
      "option": [
        {
          "name": "--all",
          "alias": [
            "-a"
          ],
          "tip": [
            "Show all tags/assets"
          ]
        },
        {
          "name": "--force",
          "alias": [
            "-f"
          ],
          "tip": [
            "Force update"
          ]
        }
      ]
    }
  ],
  "option": [
    {
      "name": "--choice",
      "tip": [
        "U: --choice [VARIANT]...",
        "List or edit choices"
      ],
      "option": [
        {
          "name": "--delete",
          "alias": [
            "-d"
          ],
          "tip": [
            "Delete given choice(s)"
          ]
        }
      ],
      "next": 0
    },
    {
      "name": "--clear-cache",
      "tip": [
        "Clear caches"
      ]
    },
    {
      "name": "--codegen",
      "tip": [
        "U: --codegen <SPEC>",
        "Generate code for spec file"
      ],
      "next": 0
    },
    {
      "name": "--condition",
      "tip": [
        "U: --condition [CONDITION]",
        "List or execute condition"
      ],
      "next": 0
    },
    {
      "name": "--detect",
      "tip": [
        "U: --detect <COMMAND>",
        "Detect bridge by invoking command"
      ],
      "next": 0
    },
    {
      "name": "--diff",
      "tip": [
        "U: --diff <COMPLETER> <COMPLETER> [...ARGS]",
        "Diff completion"
      ],
      "next": 0
    },
    {
      "name": "--edit",
      "tip": [
        "U: --edit <FILE>...",
        "Edit files"
      ],
      "next": 0
    },
    {
      "name": "--list",
      "tip": [
        "U: --list",
        "List completers"
      ],
      "option": [
        {
          "name": "--all",
          "tip": [
            "Return unfiltered results"
          ]
        },
        {
          "name": "--init",
          "tip": [
            "Update shims"
          ]
        },
        {
          "name": "--names",
          "tip": [
            "Only list names"
          ]
        }
      ]
    },
    {
      "name": "--macro",
      "tip": [
        "U: --macro [MACRO] [...ARGS]",
        "List or execute macros"
      ],
      "next": 0
    },
    {
      "name": "--mcp",
      "tip": [
        "Run MCP server"
      ]
    },
    {
      "name": "--run",
      "tip": [
        "U: --run <SPEC> [...ARGS]",
        "Run spec"
      ],
      "next": 0
    },
    {
      "name": "--schema",
      "tip": [
        "Json schema for spec files"
      ]
    },
    {
      "name": "--style",
      "tip": [
        "U: --style <KEY>=<VALUE>",
        "Set style"
      ],
      "next": 0
    },
    {
      "name": "--version",
      "alias": [
        "-v"
      ],
      "tip": [
        "U: -v, --version",
        "Show version"
      ]
    }
  ],
  "global_option": [
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "Show help"
      ]
    }
  ]
}

=== abgox/PSCompletions/completions/tombi/language/en-US.json
{
  "meta": {
    "url": "https://tombi-toml.github.io/tombi/",
    "description": [
      "TOML Toolkit"
    ]
  },
  "next": [
    {
      "name": "completion",
      "tip": [
        "U: completion <SHELL>",
        "Generate shell completion"
      ],
      "next": [
        {
          "name": "bash",
          "tip": [
            "Generate bash completion script"
          ]
        },
        {
          "name": "elvish",
          "tip": [
            "Generate elvish completion script"
          ]
        },
        {
          "name": "fish",
          "tip": [
            "Generate fish completion script"
          ]
        },
        {
          "name": "powershell",
          "tip": [
            "Generate powershell completion script"
          ]
        },
        {
          "name": "zsh",
          "tip": [
            "Generate zsh completion script"
          ]
        }
      ]
    },
    {
      "name": "format",
      "tip": [
        "Format TOML files"
      ],
      "option": [
        {
          "name": "--check",
          "tip": [
            "Check only and don't overwrite files"
          ]
        },
        {
          "name": "--diff",
          "tip": [
            "Show format changes"
          ]
        },
        {
          "name": "--no-cache",
          "tip": [
            "Do not use cache"
          ]
        },
        {
          "name": "--offline",
          "tip": [
            "Disable network access"
          ]
        },
        {
          "name": "--quiet",
          "tip": [
            "Quiet mode"
          ]
        },
        {
          "name": "--stdin-filename",
          "tip": [
            "U: --stdin-filename <STDIN_FILENAME>",
            "Filename to use when reading from stdin"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "lint",
      "tip": [
        "Lint TOML files"
      ],
      "option": [
        {
          "name": "--error-on-warnings",
          "tip": [
            "Exit with error code on warnings"
          ]
        },
        {
          "name": "--no-cache",
          "tip": [
            "Do not use cache"
          ]
        },
        {
          "name": "--offline",
          "tip": [
            "Disable network access"
          ]
        },
        {
          "name": "--quiet",
          "tip": [
            "Quiet mode"
          ]
        },
        {
          "name": "--stdin-filename",
          "tip": [
            "U: --stdin-filename <STDIN_FILENAME>",
            "Filename to use when reading from stdin"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "lsp",
      "tip": [
        "Run TOML Language Server"
      ],
      "option": [
        {
          "name": "--no-cache",
          "tip": [
            "Do not use cache"
          ]
        },
        {
          "name": "--offline",
          "tip": [
            "Disable network access"
          ]
        }
      ]
    }
  ],
  "option": [
    {
      "name": "--verbose",
      "alias": [
        "-v"
      ],
      "tip": [
        "Change the logging level",
        "-v: DEBUG, -vv: TRACE"
      ],
      "repeat": 2
    },
    {
      "name": "--version",
      "alias": [
        "-V"
      ],
      "tip": [
        "U: -V, --version",
        "Print version"
      ]
    }
  ],
  "global_option": [
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "Print help"
      ]
    }
  ]
}
