=== abgox/PSCompletions/schema/completion-manifest.zh-CN.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "required": [
    "meta"
  ],
  "definitions": {
    "string": {
      "type": "string",
      "minLength": 1
    },
    "array": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "array-items-string": {
      "$ref": "#/definitions/array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "name": {
      "title": "命令名称",
      "markdownDescription": "它应该是一个完整的名称，简写应该放在 `alias` 中",
      "examples": [
        ""
      ],
      "allOf": [
        {
          "$ref": "#/definitions/string"
        },
        {
          "if": {
            "pattern": " "
          },
          "then": {
            "pattern": "(^\".+\"$)|(^'.+'$)",
            "errorMessage": "如果需要空格，请使用 \" 或 ' 包裹，例如: 'hello world'"
          }
        }
      ]
    },
    "alias": {
      "title": "命令别名",
      "markdownDescription": "它通常是一个简写名称，完整的名称应该使用 `name` 定义",
      "examples": [
        []
      ],
      "allOf": [
        {
          "$ref": "#/definitions/array-items-string"
        },
        {
          "items": {
            "if": {
              "pattern": " "
            },
            "then": {
              "pattern": "(^\".+\"$)|(^'.+'$)",
              "errorMessage": "如果需要空格，请使用 \" 或 ' 包裹，例如: 'hello world'"
            }
          }
        }
      ]
    },
    "tip": {
      "markdownDescription": "补全的提示信息 `ToolTip`\n- 它一般由三部分组成: 用法(Usage) + 描述(Description) + 举例(Example)\n- 这里有一个示例:\n```json\n  \"tip\": [\n    \"U: -r, --revisions <REVSETS>\",\n    \"xxx (这里是描述信息)\",\n    \"E: -r '@-'   --- xxx (示例说明)\"\n    \"   -r 'x-'   --- xxx (示例说明)\"\n  ]\n  ```",
      "examples": [
        []
      ],
      "allOf": [
        {
          "$ref": "#/definitions/array-items-string"
        },
        {
          "not": {
            "contains": {
              "pattern": "[\\r\\n]"
            }
          },
          "errorMessage": "数组中的每个项会在显示时末尾自动添加换行符，因此不允许使用换行符"
        },
        {
          "items": {
            "not": {
              "pattern": "[\\u4e00-\\u9fff][A-Za-z]|[A-Za-z][\\u4e00-\\u9fff]"
            },
            "errorMessage": "中文和英文之间必须有空格"
          }
        }
      ]
    },
    "repeat": {
      "type": "number",
      "description": "该补全项的最大重复次数。",
      "minimum": 1,
      "examples": [
        1,
        2,
        3,
        4,
        5,
        99
      ]
    },
    "item": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "$ref": "#/definitions/name"
        },
        "alias": {
          "$ref": "#/definitions/alias"
        },
        "tip": {
          "$ref": "#/definitions/tip"
        },
        "repeat": {
          "$ref": "#/definitions/repeat"
        },
        "next": {
          "$ref": "#/definitions/next"
        },
        "option": {
          "$ref": "#/definitions/option"
        }
      },
      "additionalProperties": false
    },
    "next-item": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "$ref": "#/definitions/name"
        },
        "alias": {
          "$ref": "#/definitions/alias"
        },
        "tip": {
          "$ref": "#/definitions/tip"
        },
        "next": {
          "$ref": "#/definitions/next"
        },
        "option": {
          "$ref": "#/definitions/option"
        }
      },
      "additionalProperties": false
    },
    "next": {
      "markdownDescription": "下一个命令补全\n- 它可以是一个数组或数字 `0`\n- 如果是数组\n  - 数组中的项会自动添加到补全中\n  - 如果有 `hooks`，会动态添加\n- 如果是数字 `0`\n  - 它表示此时应该输入一个内容\n  - 但是 [PSCompletions](https://pscompletions.abgox.com) 无力提供补全，需要用户自行输入\n  - `0` 就是告诉 [PSCompletions](https://pscompletions.abgox.com) 应该显示 `WriteSpaceTab` 类型的符号，以实现符号预测",
      "type": [
        "array",
        "number"
      ],
      "examples": [
        [],
        0
      ],
      "uniqueItems": true,
      "items": {
        "$ref": "#/definitions/next-item"
      },
      "if": {
        "type": "number",
        "not": {
          "const": 0
        }
      },
      "then": {
        "not": true,
        "errorMessage": "next 必须是一个数组或数字 0"
      }
    },
    "option": {
      "type": "array",
      "uniqueItems": true,
      "markdownDescription": "选项类补全\n - 通常以 `-` 或 `--` 开头\n - 例如 `--list`",
      "items": {
        "$ref": "#/definitions/item"
      }
    }
  },
  "properties": {
    "meta": {
      "type": "object",
      "description": "补全命令的相关信息",
      "required": [
        "url",
        "description"
      ],
      "properties": {
        "url": {
          "description": "命令的主页或仓库地址",
          "allOf": [
            {
              "$ref": "#/definitions/string"
            },
            {
              "pattern": "^https?://",
              "errorMessage": "它必须是一个有效的 http/https URL"
            }
          ]
        },
        "description": {
          "description": "命令的描述",
          "allOf": [
            {
              "$ref": "#/definitions/array-items-string"
            },
            {
              "not": {
                "contains": {
                  "pattern": "\\n"
                }
              },
              "errorMessage": "数组中的每个项会在显示时末尾自动添加换行符，因此不允许使用换行符"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "root": {
      "description": "根命令",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/next-item"
      }
    },
    "option": {
      "markdownDescription": "根命令的选项类补全\n- 如果除了选项类补全以外，只有一个根命令，就会显示它们\n- 除非你已经使用过它或它的别名了",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/item"
      }
    },
    "common_option": {
      "markdownDescription": "通用的选项类补全\n- 任何情况下触发补全，都会显示它们\n- 除非你已经使用过它或它的别名了",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/item"
      }
    },
    "config": {
      "description": "补全的特殊配置项",
      "$ref": "#/definitions/array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "value",
          "tip"
        ],
        "properties": {
          "name": {
            "description": "配置项的名称",
            "$ref": "#/definitions/string"
          },
          "value": {
            "description": "配置项的默认值",
            "type": [
              "string",
              "number"
            ]
          },
          "values": {
            "markdownDescription": "配置项的可选值\n- 这里填写的值会在触发命令补全时显示\n - 假设命令补全是 `xxx`，配置项名称是 `enable_xxx`\n - 则当你输入 `psc completion xxx enable_xxx` 后触发补全，会获取 `values` 数组中的值，并显示在补全列表中",
            "$ref": "#/definitions/array",
            "items": {
              "type": [
                "string",
                "number"
              ]
            }
          },
          "tip": {
            "description": "配置项的提示信息",
            "$ref": "#/definitions/array-items-string"
          }
        }
      }
    },
    "info": {
      "markdownDescription": "一些额外的信息\n- 它们可以在此 json 文件的 `tip` 字段中使用 `{{ $info.xxx }}` 进行访问\n- 如果需要换行，请使用 `\\n`",
      "type": "object",
      "minProperties": 1
    }
  },
  "additionalProperties": false
}

=== abgox/PSCompletions/completions/starship/language/zh-CN.json
{
  "meta": {
    "url": "https://github.com/starship/starship",
    "description": [
      "Starship - 面向宇航员的跨 shell 提示符。"
    ]
  },
  "root": [
    {
      "name": "bug-report",
      "tip": [
        "创建包含配置信息的预填充 GitHub issue。"
      ]
    },
    {
      "name": "completions",
      "tip": [
        "为你的 shell 生成 starship shell 补全到 stdout。"
      ],
      "next": [
        {
          "name": "bash",
          "tip": [
            "生成 bash 补全脚本。"
          ]
        },
        {
          "name": "elvish",
          "tip": [
            "生成 elvish 补全脚本。"
          ]
        },
        {
          "name": "fish",
          "tip": [
            "生成 fish 补全脚本。"
          ]
        },
        {
          "name": "nushell",
          "tip": [
            "生成 nushell 补全脚本。"
          ]
        },
        {
          "name": "powershell",
          "tip": [
            "生成 PowerShell 补全脚本。"
          ]
        },
        {
          "name": "zsh",
          "tip": [
            "生成 zsh 补全脚本。"
          ]
        }
      ]
    },
    {
      "name": "config",
      "tip": [
        "编辑 starship 配置。"
      ],
      "option": [
        {
          "name": "--print",
          "tip": [
            "将默认配置打印到 stdout。"
          ]
        },
        {
          "name": "--starship",
          "tip": [
            "U: --starship <STARSHIP>",
            "指定 starship 二进制文件的路径。"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "explain",
      "tip": [
        "解释当前显示的模块。"
      ]
    },
    {
      "name": "init",
      "tip": [
        "打印用于执行 starship 的 shell 函数。"
      ],
      "next": [
        {
          "name": "bash",
          "tip": [
            "生成 bash init 脚本。"
          ]
        },
        {
          "name": "elvish",
          "tip": [
            "生成 elvish init 脚本。"
          ]
        },
        {
          "name": "fish",
          "tip": [
            "生成 fish init 脚本。"
          ]
        },
        {
          "name": "ion",
          "tip": [
            "生成 ion init 脚本。"
          ]
        },
        {
          "name": "nushell",
          "tip": [
            "生成 nushell init 脚本。"
          ]
        },
        {
          "name": "powershell",
          "tip": [
            "生成 PowerShell init 脚本。"
          ]
        },
        {
          "name": "termux",
          "tip": [
            "生成 termux init 脚本。"
          ]
        },
        {
          "name": "zsh",
          "tip": [
            "生成 zsh init 脚本。"
          ]
        }
      ]
    },
    {
      "name": "module",
      "tip": [
        "打印特定的提示模块。"
      ],
      "option": [
        {
          "name": "--cmd-duration",
          "alias": [
            "-d"
          ],
          "tip": [
            "U: -d, --cmd-duration <CMD_DURATION>",
            "最后一个命令的执行时间，以毫秒为单位。"
          ],
          "next": 0
        },
        {
          "name": "--jobs",
          "alias": [
            "-j"
          ],
          "tip": [
            "U: -j, --jobs <JOBS>",
            "当前运行的作业数。",
            "默认: 0"
          ],
          "next": 0
        },
        {
          "name": "--keymap",
          "alias": [
            "-k"
          ],
          "tip": [
            "U: -k, --keymap <KEYMAP>",
            "fish/zsh/cmd 的按键映射。",
            "默认: viins"
          ],
          "next": 0
        },
        {
          "name": "--list",
          "alias": [
            "-l"
          ],
          "tip": [
            "U: -l, --list",
            "列出所有支持的模块。"
          ]
        },
        {
          "name": "--logical-path",
          "alias": [
            "-P"
          ],
          "tip": [
            "U: -P, --logical-path <LOGICAL_PATH>",
            "提示符应渲染的逻辑路径。"
          ],
          "next": 0
        },
        {
          "name": "--path",
          "alias": [
            "-p"
          ],
          "tip": [
            "U: -p, --path <PATH>",
            "提示符应渲染的路径。"
          ],
          "next": 0
        },
        {
          "name": "--pipestatus",
          "tip": [
            "U: --pipestatus <PIPESTATUS>",
            "Bash、Fish 和 Zsh 支持返回管道中每个进程的状态码。"
          ],
          "next": 0
        },
        {
          "name": "--shlvl",
          "tip": [
            "U: --shlvl <SHLVL>",
            "SHLVL 的当前值。"
          ],
          "next": 0
        },
        {
          "name": "--status",
          "alias": [
            "-s"
          ],
          "tip": [
            "U: -s, --status <STATUS_CODE>",
            "先前运行的命令的状态码。"
          ],
          "next": 0
        },
        {
          "name": "--terminal-width",
          "alias": [
            "-w"
          ],
          "tip": [
            "U: -w, --terminal-width <TERMINAL_WIDTH>",
            "当前交互式终端的宽度。",
            "默认: 80"
          ],
          "next": 0
        }
      ],
      "next": 0
    },
    {
      "name": "preset",
      "tip": [
        "打印预设配置。"
      ],
      "next": [
        {
          "name": "'Bracketed Segments'",
          "tip": [
            "使用括号段的预设。"
          ]
        },
        {
          "name": "nerd-font-symbols",
          "tip": [
            "使用 Nerd Font 符号的预设。"
          ]
        },
        {
          "name": "no-nerd-font",
          "tip": [
            "不使用 Nerd Fonts 的预设。"
          ]
        },
        {
          "name": "no-unicode",
          "tip": [
            "不使用 Unicode 的预设。"
          ]
        },
        {
          "name": "paste-prompt",
          "tip": [
            "用于粘贴提示符的预设。"
          ]
        },
        {
          "name": "plain-directory",
          "tip": [
            "使用纯目录显示的预设。"
          ]
        },
        {
          "name": "plain-text-symbols",
          "tip": [
            "使用纯文本符号的预设。"
          ]
        }
      ]
    },
    {
      "name": "print-config",
      "tip": [
        "打印计算后的 starship 配置。"
      ]
    },
    {
      "name": "prompt",
      "tip": [
        "打印完整的 starship 提示符。"
      ],
      "option": [
        {
          "name": "--cmd-duration",
          "alias": [
            "-d"
          ],
          "tip": [
            "U: -d, --cmd-duration <CMD_DURATION>",
            "执行时间（毫秒）。"
          ],
          "next": 0
        },
        {
          "name": "--jobs",
          "alias": [
            "-j"
          ],
          "tip": [
            "U: -j, --jobs <JOBS>",
            "当前运行的作业数。"
          ],
          "next": 0
        },
        {
          "name": "--keymap",
          "alias": [
            "-k"
          ],
          "tip": [
            "U: -k, --keymap <KEYMAP>",
            "fish/zsh/cmd 的按键映射。"
          ],
          "next": 0
        },
        {
          "name": "--logical-path",
          "alias": [
            "-P"
          ],
          "tip": [
            "U: -P, --logical-path <LOGICAL_PATH>",
            "要渲染的逻辑路径。"
          ],
          "next": 0
        },
        {
          "name": "--path",
          "alias": [
            "-p"
          ],
          "tip": [
            "U: -p, --path <PATH>",
            "要渲染的路径。"
          ],
          "next": 0
        },
        {
          "name": "--pipestatus",
          "tip": [
            "U: --pipestatus <PIPESTATUS>",
            "管道中每个进程的状态码。"
          ],
          "next": 0
        },
        {
          "name": "--status",
          "alias": [
            "-s"
          ],
          "tip": [
            "U: -s, --status <STATUS_CODE>",
            "先前运行的命令的状态码。"
          ],
          "next": 0
        },
        {
          "name": "--terminal-width",
          "alias": [
            "-w"
          ],
          "tip": [
            "U: -w, --terminal-width <TERMINAL_WIDTH>",
            "终端的宽度。"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "session",
      "tip": [
        "生成随机会话密钥。"
      ]
    },
    {
      "name": "statusline",
      "tip": [
        "使用特定配置文件打印状态行。"
      ],
      "option": [
        {
          "name": "--profile",
          "tip": [
            "U: --profile <PROFILE>",
            "要使用的状态行配置文件。"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "timings",
      "tip": [
        "打印所有活动模块的时间。"
      ]
    },
    {
      "name": "toggle",
      "tip": [
        "切换给定的 starship 模块。"
      ],
      "next": 0
    }
  ],
  "option": [
    {
      "name": "--version",
      "alias": [
        "-V"
      ],
      "tip": [
        "U: -V, --version",
        "打印版本。"
      ]
    }
  ],
  "common_option": [
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "打印帮助。"
      ]
    }
  ]
}

=== abgox/PSCompletions/completions/ngrok/language/en-US.json
{
  "meta": {
    "url": "https://ngrok.com/",
    "description": [
      "ngrok - Unified Ingress Platform for developers.",
      "Connect localhost to the internet for testing applications and APIs."
    ]
  },
  "root": [
    {
      "name": "api",
      "tip": [
        "use ngrok agent as an api client"
      ]
    },
    {
      "name": "completion",
      "tip": [
        "generates shell completion code for bash or zsh"
      ]
    },
    {
      "name": "config",
      "tip": [
        "update or migrate ngrok's configuration file"
      ]
    },
    {
      "name": "credits",
      "tip": [
        "prints author and licensing information"
      ]
    },
    {
      "name": "diagnose",
      "tip": [
        "diagnose connection issues"
      ]
    },
    {
      "name": "help",
      "tip": [
        "Help about any command"
      ]
    },
    {
      "name": "http",
      "tip": [
        "start an HTTP tunnel"
      ]
    },
    {
      "name": "service",
      "tip": [
        "run and control an ngrok service on a target operating system"
      ]
    },
    {
      "name": "start",
      "tip": [
        "start endpoints or tunnels by name from the configuration file"
      ]
    },
    {
      "name": "tcp",
      "tip": [
        "start a TCP tunnel"
      ]
    },
    {
      "name": "tls",
      "tip": [
        "start a TLS tunnel"
      ]
    },
    {
      "name": "tunnel",
      "tip": [
        "start a tunnel for use with a tunnel-group backend"
      ]
    },
    {
      "name": "update",
      "tip": [
        "update ngrok to the latest version"
      ]
    },
    {
      "name": "version",
      "tip": [
        "print the version string"
      ]
    }
  ],
  "option": [
    {
      "name": "--metadata",
      "tip": [
        "Opaque user-defined metadata for the tunnel session."
      ]
    },
    {
      "name": "--version",
      "alias": [
        "-v"
      ],
      "tip": [
        "Show the version."
      ]
    }
  ],
  "common_option": [
    {
      "name": "--config",
      "tip": [
        "path to config files",
        "they are merged if multiple"
      ]
    },
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "Show the help."
      ]
    }
  ]
}

=== abgox/PSCompletions/completions/bat/language/zh-CN.json
{
  "meta": {
    "url": "https://github.com/sharkdp/bat",
    "description": [
      "一个带有语法高亮和 Git 集成的 cat(1) 克隆。"
    ]
  },
  "root": [
    {
      "name": "cache",
      "tip": [
        "U: cache [OPTIONS]",
        "自定义语法和主题。"
      ],
      "option": [
        {
          "name": "--acknowledgements",
          "tip": [
            "显示致谢信息。"
          ]
        },
        {
          "name": "--build",
          "tip": [
            "从头构建缓存。"
          ]
        },
        {
          "name": "--clear",
          "tip": [
            "删除生成的缓存文件。"
          ]
        },
        {
          "name": "--config-dir",
          "tip": [
            "显示配置目录。"
          ]
        },
        {
          "name": "--data-dir",
          "tip": [
            "显示数据目录。"
          ]
        },
        {
          "name": "--init",
          "tip": [
            "从 bat 的默认语法和主题初始化缓存。"
          ]
        }
      ]
    }
  ],
  "option": [
    {
      "name": "--acknowledgements",
      "tip": [
        "显示致谢信息。"
      ]
    },
    {
      "name": "--diagnostic",
      "tip": [
        "显示用于错误报告的诊断信息。"
      ]
    },
    {
      "name": "--list-languages",
      "alias": [
        "-L"
      ],
      "tip": [
        "U: -L, --list-languages",
        "显示支持的语言列表。"
      ]
    },
    {
      "name": "--list-themes",
      "tip": [
        "显示支持的主题列表。"
      ]
    },
    {
      "name": "--version",
      "alias": [
        "-V"
      ],
      "tip": [
        "U: -V, --version",
        "打印版本信息。"
      ]
    }
  ],
  "common_option": [
    {
      "name": "--binary",
      "tip": [
        "U: --binary <behavior>",
        "如何处理二进制内容。"
      ],
      "next": [
        {
          "name": "as-text"
        },
        {
          "name": "no-printing"
        }
      ]
    },
    {
      "name": "--chop-long-lines",
      "alias": [
        "-S"
      ],
      "tip": [
        "U: -S, --chop-long-lines",
        "截断所有超过屏幕宽度的行。"
      ]
    },
    {
      "name": "--color",
      "tip": [
        "U: --color <when>",
        "何时使用彩色输出。"
      ],
      "next": [
        {
          "name": "always"
        },
        {
          "name": "auto"
        },
        {
          "name": "never"
        }
      ]
    },
    {
      "name": "--decorations",
      "tip": [
        "U: --decorations <when>",
        "何时使用通过 --style 指定的装饰。"
      ],
      "next": [
        {
          "name": "always"
        },
        {
          "name": "auto"
        },
        {
          "name": "never"
        }
      ]
    },
    {
      "name": "--diff",
      "alias": [
        "-d"
      ],
      "tip": [
        "U: -d, --diff",
        "仅显示相对于 Git 索引添加/删除/修改的行。"
      ]
    },
    {
      "name": "--diff-context",
      "tip": [
        "U: --diff-context <N>",
        "在添加/删除/修改行周围包含 N 行上下文。"
      ],
      "next": 0
    },
    {
      "name": "--file-name",
      "tip": [
        "U: --file-name <name>",
        "指定要显示的文件名。"
      ],
      "next": 0
    },
    {
      "name": "--force-colorization",
      "alias": [
        "-f"
      ],
      "tip": [
        "U: -f, --force-colorization",
        "--decorations=always --color=always 的别名。"
      ]
    },
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "打印帮助信息。"
      ]
    },
    {
      "name": "--highlight-line",
      "alias": [
        "-H"
      ],
      "tip": [
        "U: -H, --highlight-line <N:M>",
        "高亮指定的行范围。"
      ],
      "next": 0
    },
    {
      "name": "--ignored-suffix",
      "tip": [
        "U: --ignored-suffix <suffix>",
        "忽略扩展名进行语法检测。"
      ],
      "next": 0
    },
    {
      "name": "--italic-text",
      "tip": [
        "U: --italic-text <when>",
        "何时使用 ANSI 序列显示斜体文本。"
      ],
      "next": [
        {
          "name": "always"
        },
        {
          "name": "never"
        }
      ]
    },
    {
      "name": "--language",
      "alias": [
        "-l"
      ],
      "tip": [
        "U: -l, --language <language>",
        "显式设置语法高亮的语言。"
      ],
      "next": 0
    },
    {
      "name": "--line-range",
      "alias": [
        "-r"
      ],
      "tip": [
        "U: -r, --line-range <N:M>",
        "仅打印指定范围的行。"
      ],
      "next": 0
    },
    {
      "name": "--map-syntax",
      "alias": [
        "-m"
      ],
      "tip": [
        "U: -m, --map-syntax <glob:syntax>",
        "将 glob 模式映射到现有语法名称。"
      ],
      "next": 0
    },
    {
      "name": "--nonprintable-notation",
      "tip": [
        "U: --nonprintable-notation <notation>",
        "设置不可打印字符的表示法。"
      ],
      "next": [
        {
          "name": "caret"
        },
        {
          "name": "unicode"
        }
      ]
    },
    {
      "name": "--number",
      "alias": [
        "-n"
      ],
      "tip": [
        "U: -n, --number",
        "仅显示行号，无其他装饰。"
      ]
    },
    {
      "name": "--pager",
      "tip": [
        "U: --pager <command>",
        "确定使用哪个分页器。"
      ],
      "next": 0
    },
    {
      "name": "--paging",
      "tip": [
        "U: --paging <when>",
        "何时使用分页器。"
      ],
      "next": [
        {
          "name": "always"
        },
        {
          "name": "auto"
        },
        {
          "name": "never"
        }
      ]
    },
    {
      "name": "--plain",
      "alias": [
        "-p"
      ],
      "tip": [
        "U: -p, --plain",
        "仅显示纯文本样式，无装饰。"
      ],
      "repeat": 2
    },
    {
      "name": "--set-terminal-title",
      "tip": [
        "使用分页器时将终端标题设置为文件名。"
      ]
    },
    {
      "name": "--show-all",
      "alias": [
        "-A"
      ],
      "tip": [
        "U: -A, --show-all",
        "显示不可打印字符，如空格、制表符或换行符。"
      ]
    },
    {
      "name": "--squeeze-blank",
      "alias": [
        "-s"
      ],
      "tip": [
        "U: -s, --squeeze-blank",
        "将连续空行压缩为一行。"
      ]
    },
    {
      "name": "--squeeze-limit",
      "tip": [
        "U: --squeeze-limit <limit>",
        "要打印的连续空行最大数量。"
      ],
      "next": 0
    },
    {
      "name": "--strip-ansi",
      "tip": [
        "U: --strip-ansi <when>",
        "何时剥离 ANSI 转义序列。"
      ],
      "next": [
        {
          "name": "always"
        },
        {
          "name": "auto"
        },
        {
          "name": "never"
        }
      ]
    },
    {
      "name": "--style",
      "tip": [
        "U: --style <components>",
        "配置要显示的元素。"
      ],
      "next": [
        {
          "name": "auto"
        },
        {
          "name": "changes"
        },
        {
          "name": "default"
        },
        {
          "name": "full"
        },
        {
          "name": "grid"
        },
        {
          "name": "header"
        },
        {
          "name": "header-filename"
        },
        {
          "name": "header-filesize"
        },
        {
          "name": "numbers"
        },
        {
          "name": "plain"
        },
        {
          "name": "rule"
        },
        {
          "name": "snip"
        }
      ]
    },
    {
      "name": "--tabs",
      "tip": [
        "U: --tabs <T>",
        "将制表符宽度设置为 T 个空格。"
      ],
      "next": 0
    },
    {
      "name": "--terminal-width",
      "tip": [
        "U: --terminal-width <width>",
        "显式设置终端宽度。"
      ],
      "next": 0
    },
    {
      "name": "--theme",
      "tip": [
        "U: --theme <theme>",
        "设置语法高亮的主题。"
      ],
      "next": 0
    },
    {
      "name": "--theme-dark",
      "tip": [
        "U: --theme-dark <theme>",
        "深色背景终端的主题。"
      ],
      "next": 0
    },
    {
      "name": "--theme-light",
      "tip": [
        "U: --theme-light <theme>",
        "浅色背景终端的主题。"
      ],
      "next": 0
    },
    {
      "name": "--wrap",
      "tip": [
        "U: --wrap <mode>",
        "指定文本换行模式。"
      ],
      "next": [
        {
          "name": "auto"
        },
        {
          "name": "character"
        },
        {
          "name": "never"
        }
      ]
    }
  ]
}
