=== abgox/PSCompletions/schema/completion-manifest.en-US.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "required": [
    "meta"
  ],
  "definitions": {
    "string": {
      "type": "string",
      "minLength": 1
    },
    "array": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "array-items-string": {
      "$ref": "#/definitions/array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "name": {
      "title": "Command name",
      "markdownDescription": "It should be a full name, and the short name should be in `alias`",
      "examples": [
        ""
      ],
      "allOf": [
        {
          "$ref": "#/definitions/string"
        },
        {
          "if": {
            "pattern": " "
          },
          "then": {
            "pattern": "(^\".+\"$)|(^'.+'$)",
            "errorMessage": "If spaces are needed, please use \" or ' to wrap them, for example: 'hello world'"
          }
        }
      ]
    },
    "alias": {
      "title": "Command alias",
      "markdownDescription": "It should be a short name, and the full name should be in `name`",
      "examples": [
        []
      ],
      "allOf": [
        {
          "$ref": "#/definitions/array-items-string"
        },
        {
          "items": {
            "if": {
              "pattern": " "
            },
            "then": {
              "pattern": "(^\".+\"$)|(^'.+'$)",
              "errorMessage": "If spaces are needed, please use \" or ' to wrap them, for example: 'hello world'"
            }
          }
        }
      ]
    },
    "tip": {
      "markdownDescription": "Completion item tip `ToolTip`\n- General structure of the completion tip: `Usage` + `Description` + `Example`\n- Here is an example:\n```json\n  \"tip\": [\n    \"U: -r, --revisions <REVSETS>\",\n    \"xxx (Here is the description)\",\n    \"E: -r '@-'   --- xxx (Example description)\"\n    \"   -r 'x-'   --- xxx (Example description)\"\n  ]\n  ```",
      "examples": [
        []
      ],
      "allOf": [
        {
          "$ref": "#/definitions/array-items-string"
        },
        {
          "not": {
            "contains": {
              "pattern": "[\\r\\n]"
            }
          },
          "errorMessage": "Each item in the array will automatically add a line break at the end when displayed, so line breaks are not allowed."
        },
        {
          "items": {
            "not": {
              "pattern": "[\\u4e00-\\u9fff][A-Za-z]|[A-Za-z][\\u4e00-\\u9fff]"
            },
            "errorMessage": "Chinese and English must be separated by a space"
          }
        }
      ]
    },
    "repeat": {
      "type": "number",
      "description": "Maximum number of times this item can repeat.",
      "minimum": 1,
      "examples": [
        1,
        2,
        3,
        4,
        5,
        99
      ]
    },
    "item": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "$ref": "#/definitions/name"
        },
        "alias": {
          "$ref": "#/definitions/alias"
        },
        "tip": {
          "$ref": "#/definitions/tip"
        },
        "repeat": {
          "$ref": "#/definitions/repeat"
        },
        "next": {
          "$ref": "#/definitions/next"
        },
        "option": {
          "$ref": "#/definitions/option"
        }
      },
      "additionalProperties": false
    },
    "next-item": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "$ref": "#/definitions/name"
        },
        "alias": {
          "$ref": "#/definitions/alias"
        },
        "tip": {
          "$ref": "#/definitions/tip"
        },
        "next": {
          "$ref": "#/definitions/next"
        },
        "option": {
          "$ref": "#/definitions/option"
        }
      },
      "additionalProperties": false
    },
    "next": {
      "markdownDescription": "Next subcommand completion\n- It can be an array or the number `0`\n- If it is an array\n  - Items in the array are automatically added to the completions.\n  - If there are `hooks`, they will be added dynamically.\n- If it is the number `0`\n  - It indicates that a content should be input at this time.\n  - However, [PSCompletions](https://pscompletions.abgox.com) is unable to provide completions, and users need to input manually.\n  - `0` tells [PSCompletions](https://pscompletions.abgox.com) that it should display symbols of the `WriteSpaceTab` type to achieve symbol prediction.",
      "type": [
        "array",
        "number"
      ],
      "examples": [
        [],
        0
      ],
      "uniqueItems": true,
      "items": {
        "$ref": "#/definitions/next-item"
      },
      "if": {
        "type": "number",
        "not": {
          "const": 0
        }
      },
      "then": {
        "not": true,
        "errorMessage": "It must be an array or the number 0"
      }
    },
    "option": {
      "type": "array",
      "uniqueItems": true,
      "markdownDescription": "Next optional completion\n - Usually starts with `-` or `--`\n - For example, `--list`",
      "items": {
        "$ref": "#/definitions/item"
      }
    }
  },
  "properties": {
    "meta": {
      "type": "object",
      "description": "Additional information for the completion command",
      "required": [
        "url",
        "description"
      ],
      "properties": {
        "url": {
          "description": "Homepage or repository address of the completion command",
          "allOf": [
            {
              "$ref": "#/definitions/string"
            },
            {
              "pattern": "^https?://",
              "errorMessage": "It must be a valid http/https URL"
            }
          ]
        },
        "description": {
          "description": "Description of the completion command",
          "allOf": [
            {
              "$ref": "#/definitions/array-items-string"
            },
            {
              "not": {
                "contains": {
                  "pattern": "\\n"
                }
              },
              "errorMessage": "Each item in the array will automatically add a line break at the end when displayed, so line breaks are not allowed."
            },
            {
              "items": {
                "not": {
                  "pattern": "[\\u4e00-\\u9fff][A-Za-z]|[A-Za-z][\\u4e00-\\u9fff]"
                },
                "errorMessage": "Chinese and English must be separated by a space"
              }
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "next": {
      "description": "Subcommand completion for the root command",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/next-item"
      }
    },
    "option": {
      "markdownDescription": "Optional completion for the root command",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/item"
      }
    },
    "global_option": {
      "markdownDescription": "Global optional completion\n- Any time you trigger completion, they will be displayed\n- Unless you have used it or its alias",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/item"
      }
    },
    "config": {
      "description": "Special configuration items for the completion command",
      "$ref": "#/definitions/array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "value",
          "tip"
        ],
        "properties": {
          "name": {
            "description": "Name of the special configuration item",
            "$ref": "#/definitions/string"
          },
          "value": {
            "description": "Default value of the special configuration item",
            "type": [
              "string",
              "number"
            ]
          },
          "values": {
            "markdownDescription": "Optional values of the special configuration item\n- Here, you can fill in the values that will be displayed when the command completion is triggered\n - Suppose the command completion is `xxx` and the configuration item name is `enable_xxx`\n - Then, when you input `psc completion xxx enable_xxx` and trigger completion, the values in the `values` array will be displayed in the completion list",
            "$ref": "#/definitions/array",
            "items": {
              "type": [
                "string",
                "number"
              ]
            }
          },
          "tip": {
            "description": "Tip information for the special configuration item",
            "$ref": "#/definitions/array-items-string"
          }
        }
      }
    },
    "info": {
      "markdownDescription": "Additional information\n- They can be accessed in the `tip` field of this json file using `{{ $info.xxx }}`\n- If you need to add line breaks, please use `\\n`",
      "type": "object",
      "minProperties": 1
    }
  },
  "additionalProperties": false
}

=== abgox/PSCompletions/completions/ya/language/en-US.json
{
  "meta": {
    "url": "https://yazi-rs.github.io/",
    "description": [
      "Yazi - Blazing fast terminal file manager written in Rust."
    ]
  },
  "next": [
    {
      "name": "emit",
      "tip": [
        "U: emit <NAME> [ARGS]...",
        "Emit an action to be executed by the current instance"
      ]
    },
    {
      "name": "emit-to",
      "tip": [
        "U: emit-to <RECEIVER> <NAME> [ARGS]...",
        "Emit an action to be executed by the specified instance"
      ]
    },
    {
      "name": "exec",
      "tip": [
        "U: exec <NAME> [ARGS]...",
        "Execute an action on the current instance and print its result"
      ]
    },
    {
      "name": "help",
      "tip": [
        "Print this message or the help of the given subcommand(s)"
      ]
    },
    {
      "name": "pkg",
      "tip": [
        "Manage packages"
      ],
      "next": [
        {
          "name": "add",
          "tip": [
            "Add packages"
          ]
        },
        {
          "name": "delete",
          "tip": [
            "Delete packages"
          ],
          "next": []
        },
        {
          "name": "help",
          "tip": [
            "Print this message or the help of the given subcommand(s)"
          ]
        },
        {
          "name": "install",
          "tip": [
            "Install all packages"
          ]
        },
        {
          "name": "list",
          "tip": [
            "List all packages"
          ]
        },
        {
          "name": "upgrade",
          "tip": [
            "Upgrade all packages"
          ],
          "next": []
        }
      ]
    },
    {
      "name": "pub",
      "tip": [
        "U: pub [OPTIONS] <KIND>",
        "Publish a message to the current instance"
      ],
      "option": [
        {
          "name": "--json",
          "tip": [
            "U: --json <JSON>",
            "Send the message with a JSON body"
          ]
        },
        {
          "name": "--list",
          "tip": [
            "U: --list [<LIST>...]",
            "Send the message as a list of strings"
          ],
          "next": 0
        },
        {
          "name": "--str",
          "tip": [
            "U: --str <STR>",
            "Send the message with a string body"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "pub-to",
      "tip": [
        "U: pub-to [OPTIONS] <RECEIVER> <KIND>",
        "Publish a message to the specified instance"
      ],
      "option": [
        {
          "name": "--json",
          "tip": [
            "U: --json <JSON>",
            "Send the message with a JSON body"
          ]
        },
        {
          "name": "--list",
          "tip": [
            "U: --list [<LIST>...]",
            "Send the message as a list of strings"
          ],
          "next": 0
        },
        {
          "name": "--str",
          "tip": [
            "U: --str <STR>",
            "Send the message with a string body"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "sub",
      "tip": [
        "U: sub <KINDS>",
        "Subscribe to messages from all remote instances"
      ]
    }
  ],
  "option": [
    {
      "name": "--version",
      "alias": [
        "-V"
      ],
      "tip": [
        "U: -V, --version",
        "Show the version."
      ]
    }
  ],
  "global_option": [
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "Show the help."
      ]
    }
  ]
}

=== abgox/PSCompletions/completions/mcfly/language/zh-CN.json
{
  "meta": {
    "url": "https://github.com/cantino/mcfly",
    "description": [
      "在 Shell 历史记录中快速穿梭"
    ]
  },
  "next": [
    {
      "name": "add",
      "tip": [
        "U: add [OPTIONS] [COMMAND]...",
        "将命令添加到历史记录"
      ],
      "option": [
        {
          "name": "--append-to-histfile",
          "alias": [
            "-a"
          ],
          "tip": [
            "U: -a, --append-to-histfile <HISTFILE>",
            "同时将命令追加到指定文件"
          ],
          "next": 0
        },
        {
          "name": "--dir",
          "alias": [
            "-d"
          ],
          "tip": [
            "U: -d, --dir <PATH>",
            "命令执行时的目录（默认 $PWD）"
          ],
          "next": 0
        },
        {
          "name": "--exit",
          "alias": [
            "-e"
          ],
          "tip": [
            "U: -e, --exit <EXIT_CODE>",
            "命令的退出码"
          ],
          "next": 0
        },
        {
          "name": "--old-dir",
          "alias": [
            "-o"
          ],
          "tip": [
            "U: -o, --old-dir <PATH>",
            "执行命令前用户所在的目录（默认 $OLDPWD）"
          ],
          "next": 0
        },
        {
          "name": "--when",
          "alias": [
            "-w"
          ],
          "tip": [
            "U: -w, --when <UNIX_EPOCH>",
            "命令执行的时间（默认为当前时间）"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "dump",
      "tip": [
        "U: dump [OPTIONS]",
        "将历史记录输出到标准输出；结果按时间戳排序"
      ],
      "option": [
        {
          "name": "--before",
          "tip": [
            "U: --before <BEFORE>",
            "选择在此时间点之前运行的所有命令"
          ],
          "next": 0
        },
        {
          "name": "--format",
          "alias": [
            "-f"
          ],
          "tip": [
            "U: -f, --format <FORMAT>",
            "输出格式（默认 json）"
          ],
          "next": [
            {
              "name": "csv",
              "tip": [
                "CSV 格式"
              ]
            },
            {
              "name": "json",
              "tip": [
                "JSON 格式"
              ]
            }
          ]
        },
        {
          "name": "--regex",
          "alias": [
            "-r"
          ],
          "tip": [
            "U: -r, --regex <REGEX>",
            "要求命令匹配指定的正则表达式"
          ],
          "next": 0
        },
        {
          "name": "--since",
          "tip": [
            "U: --since <SINCE>",
            "选择在此时间点之后运行的所有命令"
          ],
          "next": 0
        },
        {
          "name": "--sort",
          "alias": [
            "-s"
          ],
          "tip": [
            "U: -s, --sort <ORDER>",
            "排序方式（默认 ASC）"
          ],
          "next": [
            {
              "name": "ASC",
              "tip": [
                "升序"
              ]
            },
            {
              "name": "DESC",
              "tip": [
                "降序"
              ]
            }
          ]
        }
      ]
    },
    {
      "name": "init",
      "tip": [
        "U: init <SHELL>",
        "输出用于执行 mcfly 的 shell 代码"
      ],
      "next": [
        {
          "name": "bash",
          "tip": [
            "为 bash 初始化"
          ]
        },
        {
          "name": "fish",
          "tip": [
            "为 fish 初始化"
          ]
        },
        {
          "name": "powershell",
          "tip": [
            "为 powershell 初始化"
          ]
        },
        {
          "name": "zsh",
          "tip": [
            "为 zsh 初始化"
          ]
        }
      ]
    },
    {
      "name": "move",
      "tip": [
        "U: move <OLD_DIR_PATH> <NEW_DIR_PATH>",
        "记录目录移动；将命令记录从旧路径迁移到新路径"
      ]
    },
    {
      "name": "search",
      "tip": [
        "U: search [OPTIONS] [COMMAND]...",
        "搜索历史记录"
      ],
      "option": [
        {
          "name": "--delete_without_confirm",
          "tip": [
            "无需确认直接删除条目"
          ]
        },
        {
          "name": "--dir",
          "alias": [
            "-d"
          ],
          "tip": [
            "U: -d, --dir <PATH>",
            "命令执行时的目录（默认 $PWD）"
          ],
          "next": 0
        },
        {
          "name": "--fuzzy",
          "alias": [
            "-f"
          ],
          "tip": [
            "U: -f, --fuzzy <FUZZY>",
            "模糊搜索结果。0 为关闭；数值越高，越倾向于匹配较短或较早的记录"
          ],
          "next": 0
        },
        {
          "name": "--output-selection",
          "alias": [
            "-o"
          ],
          "tip": [
            "U: -o, --output-selection <PATH>",
            "将结果写入文件，包含选择模式、新命令行以及特定 shell 的请求"
          ],
          "next": 0
        },
        {
          "name": "--results",
          "alias": [
            "-r"
          ],
          "tip": [
            "U: -r, --results <NUMBER>",
            "返回的结果数量"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "stats",
      "tip": [
        "U: stats [OPTIONS]",
        "输出统计信息"
      ],
      "option": [
        {
          "name": "--cmds",
          "alias": [
            "-c"
          ],
          "tip": [
            "U: -c, --cmds <cmds>",
            "\"top-n\"命令的数量（默认: 10）"
          ],
          "next": 0
        },
        {
          "name": "--dirs",
          "alias": [
            "-d"
          ],
          "tip": [
            "U: -d, --dirs <dirs>",
            "按顶级目录分类显示（默认: 0，即不限制目录）"
          ],
          "next": 0
        },
        {
          "name": "--global-commands-to-ignore",
          "alias": [
            "-g"
          ],
          "tip": [
            "U: -g, --global-commands-to-ignore <global_cmds_to_ignore>",
            "全局忽略的命令数量（默认: 10）"
          ],
          "next": 0
        },
        {
          "name": "--min-cmd-length",
          "alias": [
            "-m"
          ],
          "tip": [
            "U: -m, --min-cmd-length <min_cmd_length>",
            "列入\"top-n\"命令的最小命令长度（默认: 0）"
          ],
          "next": 0
        },
        {
          "name": "--only-dir",
          "alias": [
            "-o"
          ],
          "tip": [
            "U: -o, --only-dir <ONLY_DIR>",
            "仅显示来自指定目录的命令"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "train",
      "tip": [
        "U: train [OPTIONS]",
        "训练建议引擎（开发者工具）"
      ],
      "option": [
        {
          "name": "--refresh_cache",
          "alias": [
            "-r"
          ],
          "tip": [
            "U: -r, --refresh_cache",
            "刷新建议缓存"
          ]
        }
      ]
    }
  ],
  "option": [
    {
      "name": "--debug",
      "alias": [
        "-d"
      ],
      "tip": [
        "U: -d, --debug",
        "调试模式"
      ]
    },
    {
      "name": "--history_format",
      "tip": [
        "U: --history_format <FORMAT>",
        "Shell 历史文件格式（默认: bash）"
      ],
      "next": [
        {
          "name": "bash",
          "tip": [
            "Bash 历史格式"
          ]
        },
        {
          "name": "fish",
          "tip": [
            "Fish 历史格式"
          ]
        },
        {
          "name": "zsh",
          "tip": [
            "Zsh 历史格式"
          ]
        },
        {
          "name": "zsh-extended",
          "tip": [
            "Zsh 扩展历史格式"
          ]
        }
      ]
    },
    {
      "name": "--mcfly_history",
      "tip": [
        "U: --mcfly_history <MCFLY_HISTORY>",
        "添加或搜索时读取的 shell 历史文件（默认 $MCFLY_HISTORY）"
      ],
      "next": 0
    },
    {
      "name": "--session_id",
      "tip": [
        "U: --session_id <SESSION_ID>",
        "记录或搜索时使用的会话 ID（默认 $MCFLY_SESSION_ID）"
      ],
      "next": 0
    },
    {
      "name": "--version",
      "alias": [
        "-V"
      ],
      "tip": [
        "U: -V, --version",
        "打印版本信息"
      ]
    }
  ],
  "global_option": [
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "打印帮助信息"
      ]
    }
  ]
}

=== abgox/PSCompletions/completions/sfsu/language/en-US.json
{
  "meta": {
    "url": "https://github.com/winpax/sfsu",
    "description": [
      "Scoop utilities, 30-100x faster than native Scoop."
    ]
  },
  "next": [
    {
      "name": "app",
      "tip": [
        "Commands for managing apps"
      ]
    },
    {
      "name": "bucket",
      "tip": [
        "Commands for managing buckets"
      ]
    },
    {
      "name": "cache",
      "tip": [
        "Show or clear the download cache"
      ]
    },
    {
      "name": "cat",
      "tip": [
        "Show content of specified manifest"
      ]
    },
    {
      "name": "checkup",
      "tip": [
        "Check for common issues"
      ]
    },
    {
      "name": "credits",
      "tip": [
        "Show credits"
      ]
    },
    {
      "name": "depends",
      "tip": [
        "List the dependencies of a given package, in the order that they will be installed"
      ]
    },
    {
      "name": "describe",
      "tip": [
        "Describe a package"
      ]
    },
    {
      "name": "download",
      "tip": [
        "Download the specified app"
      ]
    },
    {
      "name": "export",
      "tip": [
        "Exports installed apps, buckets (and optionally configs) in JSON format"
      ]
    },
    {
      "name": "help",
      "tip": [
        "Print this message or the help of the given subcommand(s)"
      ]
    },
    {
      "name": "home",
      "tip": [
        "Opens the app homepage"
      ]
    },
    {
      "name": "hook",
      "tip": [
        "Generate hooks for the given shell"
      ]
    },
    {
      "name": "info",
      "tip": [
        "Display information about a package"
      ]
    },
    {
      "name": "list",
      "tip": [
        "List all installed packages"
      ]
    },
    {
      "name": "outdated",
      "tip": [
        "List outdated buckets and/or packages"
      ]
    },
    {
      "name": "scan",
      "tip": [
        "Scan a file with `VirusTotal`"
      ]
    },
    {
      "name": "search",
      "tip": [
        "Search for a package"
      ]
    },
    {
      "name": "status",
      "tip": [
        "Show status and check for new app versions"
      ]
    },
    {
      "name": "unused-buckets",
      "tip": [
        "Find buckets that do not have any installed packages"
      ]
    },
    {
      "name": "update",
      "tip": [
        "Update Scoop and Scoop buckets"
      ]
    }
  ],
  "option": [
    {
      "name": "--version",
      "alias": [
        "-V"
      ],
      "tip": [
        "U: -V, --version",
        "Show the version."
      ]
    }
  ],
  "global_option": [
    {
      "name": "--assume-yes",
      "alias": [
        "-y"
      ],
      "tip": [
        "U: -y, --assume-yes",
        "Assume \"yes\" as answer to prompts"
      ]
    },
    {
      "name": "--disable-git",
      "tip": [
        "Disable using git commands for certain parts of the program.",
        "Allows sfsu to work entirely if you don't have git installed, but can negatively affect performance.",
        "[env: DISABLE_GIT=]"
      ]
    },
    {
      "name": "--global",
      "alias": [
        "-g"
      ],
      "tip": [
        "U: -g, --global",
        "Use the global Scoop context"
      ]
    },
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "Show the help."
      ]
    },
    {
      "name": "--json",
      "tip": [
        "Print in the raw JSON output, rather than a human readable format"
      ]
    },
    {
      "name": "--no-color",
      "tip": [
        "Disable terminal formatting",
        "[env: NO_COLOR=]"
      ]
    },
    {
      "name": "--verbose",
      "alias": [
        "-v"
      ],
      "tip": [
        "U: -v, --verbose",
        "Enable verbose logging"
      ]
    }
  ]
}

=== abgox/PSCompletions/completions/zoxide/language/zh-CN.json
{
  "meta": {
    "url": "https://github.com/ajeetdsouza/zoxide",
    "description": [
      "更智能的 cd 命令。"
    ]
  },
  "next": [
    {
      "name": "add",
      "tip": [
        "U: add [OPTIONS] <PATHS>...",
        "添加一个新目录或增加其排名"
      ],
      "option": [
        {
          "name": "--score",
          "alias": [
            "-s"
          ],
          "tip": [
            "U: -s, --score <SCORE>",
            "如果条目存在，则增加其排名；如果不存在，则初始化其排名"
          ],
          "next": 0
        }
      ]
    },
    {
      "name": "edit",
      "tip": [
        "编辑数据库"
      ]
    },
    {
      "name": "import",
      "tip": [
        "U: import [OPTIONS] --from <FROM> <PATH>",
        "从另一个应用程序导入条目"
      ],
      "option": [
        {
          "name": "--from",
          "tip": [
            "U: --from <FROM>",
            "从哪个应用程序导入条目"
          ],
          "next": [
            {
              "name": "autojump"
            },
            {
              "name": "z"
            }
          ]
        },
        {
          "name": "--merge",
          "tip": [
            "合并到现有数据库"
          ]
        }
      ]
    },
    {
      "name": "init",
      "tip": [
        "U: init [OPTIONS] <SHELL>",
        "生成 shell 配置"
      ],
      "option": [
        {
          "name": "--cmd",
          "tip": [
            "U: --cmd <CMD>",
            "更改 z 和 zi 命令的前缀 [默认值: z]"
          ],
          "next": [
            {
              "name": "z",
              "tip": [
                "默认值"
              ]
            }
          ]
        },
        {
          "name": "--hook",
          "tip": [
            "U: --hook <HOOK>",
            "更改 zoxide 增加目录排名的频率 [默认值: pwd]"
          ],
          "next": [
            {
              "name": "none"
            },
            {
              "name": "prompt"
            },
            {
              "name": "pwd"
            }
          ]
        },
        {
          "name": "--no-cmd",
          "tip": [
            "U: --no-cmd",
            "防止 zoxide 定义 z 和 zi 命令"
          ]
        }
      ],
      "next": [
        {
          "name": "bash"
        },
        {
          "name": "elvish"
        },
        {
          "name": "fish"
        },
        {
          "name": "nushell"
        },
        {
          "name": "posix"
        },
        {
          "name": "powershell"
        },
        {
          "name": "tcsh"
        },
        {
          "name": "xonsh"
        },
        {
          "name": "zsh"
        }
      ]
    },
    {
      "name": "query",
      "tip": [
        "U: query [OPTIONS] [KEYWORDS]...",
        "在数据库中搜索目录"
      ],
      "option": [
        {
          "name": "--base-dir",
          "tip": [
            "U: --base-dir <path>",
            "只在此目录内搜索"
          ]
        },
        {
          "name": "--exclude",
          "tip": [
            "U: --exclude <path>",
            "排除当前目录"
          ]
        },
        {
          "name": "-a",
          "tip": [
            "U: -a, --all",
            "显示不可用目录"
          ]
        },
        {
          "name": "-i",
          "tip": [
            "U: -i, --interactive",
            "使用交互式选择"
          ]
        },
        {
          "name": "-l",
          "tip": [
            "U: -l, --list",
            "列出所有匹配目录"
          ]
        },
        {
          "name": "-s",
          "tip": [
            "U: -s, --score",
            "打印结果的分数"
          ]
        }
      ]
    },
    {
      "name": "remove",
      "tip": [
        "U: remove [PATHS]...",
        "从数据库中删除目录"
      ],
      "next": []
    }
  ],
  "option": [
    {
      "name": "--version",
      "alias": [
        "-V"
      ],
      "tip": [
        "U: -V, --version",
        "显示版本信息。"
      ]
    }
  ],
  "global_option": [
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "显示帮助信息。"
      ]
    }
  ]
}
