=== abgox/PSCompletions/schema/completion-manifest.zh-CN.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "required": [
    "meta"
  ],
  "definitions": {
    "string": {
      "type": "string",
      "minLength": 1
    },
    "array": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true
    },
    "array-items-string": {
      "$ref": "#/definitions/array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "name": {
      "title": "命令名称",
      "markdownDescription": "它应该是一个完整的名称，简写应该放在 `alias` 中",
      "examples": [
        ""
      ],
      "allOf": [
        {
          "$ref": "#/definitions/string"
        },
        {
          "if": {
            "pattern": " "
          },
          "then": {
            "pattern": "(^\".+\"$)|(^'.+'$)",
            "errorMessage": "如果需要空格，请使用 \" 或 ' 包裹，例如: 'hello world'"
          }
        }
      ]
    },
    "alias": {
      "title": "命令别名",
      "markdownDescription": "它通常是一个简写名称，完整的名称应该使用 `name` 定义",
      "examples": [
        []
      ],
      "allOf": [
        {
          "$ref": "#/definitions/array-items-string"
        },
        {
          "items": {
            "if": {
              "pattern": " "
            },
            "then": {
              "pattern": "(^\".+\"$)|(^'.+'$)",
              "errorMessage": "如果需要空格，请使用 \" 或 ' 包裹，例如: 'hello world'"
            }
          }
        }
      ]
    },
    "tip": {
      "markdownDescription": "补全的提示信息 `ToolTip`\n- 它一般由三部分组成: 用法(Usage) + 描述(Description) + 举例(Example)\n- 这里有一个示例:\n```json\n  \"tip\": [\n    \"U: -r, --revisions <REVSETS>\",\n    \"xxx (这里是描述信息)\",\n    \"E: -r '@-'   --- xxx (示例说明)\"\n    \"   -r 'x-'   --- xxx (示例说明)\"\n  ]\n  ```",
      "examples": [
        []
      ],
      "allOf": [
        {
          "$ref": "#/definitions/array-items-string"
        },
        {
          "not": {
            "contains": {
              "pattern": "[\\r\\n]"
            }
          },
          "errorMessage": "数组中的每个项会在显示时末尾自动添加换行符，因此不允许使用换行符"
        },
        {
          "items": {
            "not": {
              "pattern": "[\\u4e00-\\u9fff][A-Za-z]|[A-Za-z][\\u4e00-\\u9fff]"
            },
            "errorMessage": "中文和英文之间必须有空格"
          }
        }
      ]
    },
    "repeat": {
      "type": "number",
      "description": "该补全项的最大重复次数。",
      "minimum": 1,
      "examples": [
        1,
        2,
        3,
        4,
        5,
        99
      ]
    },
    "item": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "$ref": "#/definitions/name"
        },
        "alias": {
          "$ref": "#/definitions/alias"
        },
        "tip": {
          "$ref": "#/definitions/tip"
        },
        "repeat": {
          "$ref": "#/definitions/repeat"
        },
        "next": {
          "$ref": "#/definitions/next"
        },
        "option": {
          "$ref": "#/definitions/option"
        }
      },
      "additionalProperties": false
    },
    "next-item": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "name": {
          "$ref": "#/definitions/name"
        },
        "alias": {
          "$ref": "#/definitions/alias"
        },
        "tip": {
          "$ref": "#/definitions/tip"
        },
        "next": {
          "$ref": "#/definitions/next"
        },
        "option": {
          "$ref": "#/definitions/option"
        }
      },
      "additionalProperties": false
    },
    "next": {
      "markdownDescription": "下一个命令补全\n- 它可以是一个数组或数字 `0`\n- 如果是数组\n  - 数组中的项会自动添加到补全中\n  - 如果有 `hooks`，会动态添加\n- 如果是数字 `0`\n  - 它表示此时应该输入一个内容\n  - 但是 [PSCompletions](https://pscompletions.abgox.com) 无力提供补全，需要用户自行输入\n  - `0` 就是告诉 [PSCompletions](https://pscompletions.abgox.com) 应该显示 `WriteSpaceTab` 类型的符号，以实现符号预测",
      "type": [
        "array",
        "number"
      ],
      "examples": [
        [],
        0
      ],
      "uniqueItems": true,
      "items": {
        "$ref": "#/definitions/next-item"
      },
      "if": {
        "type": "number",
        "not": {
          "const": 0
        }
      },
      "then": {
        "not": true,
        "errorMessage": "next 必须是一个数组或数字 0"
      }
    },
    "option": {
      "type": "array",
      "uniqueItems": true,
      "markdownDescription": "选项类补全\n - 通常以 `-` 或 `--` 开头\n - 例如 `--list`",
      "items": {
        "$ref": "#/definitions/item"
      }
    }
  },
  "properties": {
    "meta": {
      "type": "object",
      "description": "补全命令的相关信息",
      "required": [
        "url",
        "description"
      ],
      "properties": {
        "url": {
          "description": "命令的主页或仓库地址",
          "allOf": [
            {
              "$ref": "#/definitions/string"
            },
            {
              "pattern": "^https?://",
              "errorMessage": "它必须是一个有效的 http/https URL"
            }
          ]
        },
        "description": {
          "description": "命令的描述",
          "allOf": [
            {
              "$ref": "#/definitions/array-items-string"
            },
            {
              "not": {
                "contains": {
                  "pattern": "\\n"
                }
              },
              "errorMessage": "数组中的每个项会在显示时末尾自动添加换行符，因此不允许使用换行符"
            }
          ]
        }
      },
      "additionalProperties": false
    },
    "root": {
      "description": "根命令",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/next-item"
      }
    },
    "option": {
      "markdownDescription": "根命令的选项类补全\n- 如果除了选项类补全以外，只有一个根命令，就会显示它们\n- 除非你已经使用过它或它的别名了",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/item"
      }
    },
    "common_option": {
      "markdownDescription": "通用的选项类补全\n- 任何情况下触发补全，都会显示它们\n- 除非你已经使用过它或它的别名了",
      "$ref": "#/definitions/array",
      "items": {
        "$ref": "#/definitions/item"
      }
    },
    "config": {
      "description": "补全的特殊配置项",
      "$ref": "#/definitions/array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "value",
          "tip"
        ],
        "properties": {
          "name": {
            "description": "配置项的名称",
            "$ref": "#/definitions/string"
          },
          "value": {
            "description": "配置项的默认值",
            "type": [
              "string",
              "number"
            ]
          },
          "values": {
            "markdownDescription": "配置项的可选值\n- 这里填写的值会在触发命令补全时显示\n - 假设命令补全是 `xxx`，配置项名称是 `enable_xxx`\n - 则当你输入 `psc completion xxx enable_xxx` 后触发补全，会获取 `values` 数组中的值，并显示在补全列表中",
            "$ref": "#/definitions/array",
            "items": {
              "type": [
                "string",
                "number"
              ]
            }
          },
          "tip": {
            "description": "配置项的提示信息",
            "$ref": "#/definitions/array-items-string"
          }
        }
      }
    },
    "info": {
      "markdownDescription": "一些额外的信息\n- 它们可以在此 json 文件的 `tip` 字段中使用 `{{ $info.xxx }}` 进行访问\n- 如果需要换行，请使用 `\\n`",
      "type": "object",
      "minProperties": 1
    }
  },
  "additionalProperties": false
}

=== abgox/PSCompletions/completions/adb/language/zh-CN.json
{
  "meta": {
    "url": "https://developer.android.com/tools/adb",
    "description": [
      "adb 是一个命令行工具，用于与设备通信。"
    ]
  },
  "root": [
    {
      "name": "bugreport",
      "tip": [
        "U: bugreport [PATH]",
        "将 bugreport 写入指定的 PATH"
      ]
    },
    {
      "name": "connect",
      "tip": [
        "U: connect HOST[:PORT]",
        "通过 TCP/IP 连接设备 [默认端口=5555]"
      ]
    },
    {
      "name": "devices",
      "tip": [
        "列出已连接的设备（-l 显示详细信息）"
      ],
      "option": [
        {
          "name": "-l",
          "tip": [
            "显示详细输出"
          ]
        }
      ]
    },
    {
      "name": "disable-verity",
      "tip": [
        "在 userdebug 构建中禁用 dm-verity 检查"
      ]
    },
    {
      "name": "disconnect",
      "tip": [
        "U: disconnect [HOST[:PORT]]",
        "断开与指定 TCP/IP 设备的连接 [默认端口=5555]，或断开所有连接"
      ]
    },
    {
      "name": "emu",
      "tip": [
        "U: emu COMMAND",
        "运行模拟器控制台命令"
      ]
    },
    {
      "name": "enable-verity",
      "tip": [
        "在 userdebug 构建中重新启用 dm-verity 检查"
      ]
    },
    {
      "name": "forward",
      "tip": [
        "U: forward LOCAL REMOTE",
        "使用端口转发套接字连接"
      ],
      "option": [
        {
          "name": "--list",
          "tip": [
            "列出所有转发套接字连接"
          ]
        },
        {
          "name": "--no-rebind",
          "tip": [
            "不替换现有连接"
          ]
        },
        {
          "name": "--remove",
          "tip": [
            "U: --remove LOCAL",
            "移除指定的转发套接字连接"
          ]
        },
        {
          "name": "--remove-all",
          "tip": [
            "移除所有转发套接字连接"
          ]
        }
      ]
    },
    {
      "name": "get-devpath",
      "tip": [
        "打印 <device-path>"
      ]
    },
    {
      "name": "get-serialno",
      "tip": [
        "打印 <serial-number>"
      ]
    },
    {
      "name": "get-state",
      "tip": [
        "打印 offline | bootloader | device"
      ]
    },
    {
      "name": "help",
      "tip": [
        "显示此帮助信息"
      ]
    },
    {
      "name": "install",
      "tip": [
        "U: install PACKAGE",
        "推送单个安装包到设备并安装"
      ]
    },
    {
      "name": "install-multi-package",
      "tip": [
        "推送一个或多个安装包到设备并原子化安装"
      ]
    },
    {
      "name": "install-multiple",
      "tip": [
        "U: install-multiple PACKAGE...",
        "推送多个 APK 到设备作为单个包并安装"
      ]
    },
    {
      "name": "jdwp",
      "tip": [
        "列出托管 JDWP 传输的进程 PID"
      ]
    },
    {
      "name": "keygen",
      "tip": [
        "U: keygen FILE",
        "生成 adb 公钥/私钥；私钥存储在 FILE 中"
      ]
    },
    {
      "name": "kill-server",
      "tip": [
        "如果服务器正在运行则终止它"
      ]
    },
    {
      "name": "logcat",
      "tip": [
        "显示设备日志（logcat --help 查看更多信息）"
      ]
    },
    {
      "name": "ppp",
      "tip": [
        "U: ppp TTY [PARAMETER...]",
        "通过 USB 运行 PPP"
      ]
    },
    {
      "name": "pull",
      "tip": [
        "从设备复制文件/目录"
      ]
    },
    {
      "name": "push",
      "tip": [
        "将本地文件/目录复制到设备"
      ]
    },
    {
      "name": "reboot",
      "tip": [
        "U: reboot (bootloader|recovery|sideload|sideload-auto-reboot)",
        "重启设备；默认启动系统镜像"
      ]
    },
    {
      "name": "reconnect",
      "tip": [
        "从主机端断开连接以强制重新连接"
      ]
    },
    {
      "name": "remount",
      "tip": [
        "以读写方式重新挂载分区。"
      ],
      "option": [
        {
          "name": "-R",
          "tip": [
            "在将系统分区以读写方式重新挂载后，将其重新挂载为只读。"
          ]
        }
      ]
    },
    {
      "name": "reverse",
      "tip": [
        "U: reverse LOCAL REMOTE",
        "反向套接字连接"
      ],
      "option": [
        {
          "name": "--list",
          "tip": [
            "列出设备的所有反向套接字连接"
          ]
        },
        {
          "name": "--no-rebind",
          "tip": [
            "不替换现有连接"
          ]
        },
        {
          "name": "--remove",
          "tip": [
            "U: --remove REMOTE",
            "移除指定的反向套接字连接"
          ]
        },
        {
          "name": "--remove-all",
          "tip": [
            "移除设备的所有反向套接字连接"
          ]
        }
      ]
    },
    {
      "name": "root",
      "tip": [
        "以 root 权限重启 adbd"
      ]
    },
    {
      "name": "shell",
      "tip": [
        "运行远程 shell 命令（未指定命令时启动交互式 shell）"
      ]
    },
    {
      "name": "sideload",
      "tip": [
        "U: sideload OTAPACKAGE",
        "侧载指定的完整 OTA 包"
      ]
    },
    {
      "name": "start-server",
      "tip": [
        "确保服务器正在运行"
      ]
    },
    {
      "name": "sync",
      "tip": [
        "将 $ANDROID_PRODUCT_OUT 中的本地构建同步到设备（默认全部）"
      ]
    },
    {
      "name": "tcpip",
      "tip": [
        "U: tcpip PORT",
        "重启 adbd 并在 PORT 上监听 TCP"
      ]
    },
    {
      "name": "uninstall",
      "tip": [
        "U: uninstall PACKAGE",
        "从设备移除此应用包"
      ],
      "option": [
        {
          "name": "-k",
          "tip": [
            "保留数据和缓存目录"
          ]
        }
      ]
    },
    {
      "name": "unroot",
      "tip": [
        "以非 root 权限重启 adbd"
      ]
    },
    {
      "name": "usb",
      "tip": [
        "重启 adbd 并通过 USB 监听"
      ]
    },
    {
      "name": "version",
      "tip": [
        "显示版本号"
      ]
    },
    {
      "name": "wait-for-bootloader",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-device",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-disconnect",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-local-bootloader",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-local-device",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-local-disconnect",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-local-recovery",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-local-rescue",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-local-sideload",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-recovery",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-rescue",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-sideload",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-usb-bootloader",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-usb-device",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-usb-disconnect",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-usb-recovery",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-usb-rescue",
      "tip": [
        "等待设备进入指定状态"
      ]
    },
    {
      "name": "wait-for-usb-sideload",
      "tip": [
        "等待设备进入指定状态"
      ]
    }
  ],
  "option": [
    {
      "name": "--version",
      "tip": [
        "显示版本信息。"
      ]
    }
  ],
  "common_option": [
    {
      "name": "--help",
      "tip": [
        "显示帮助信息。"
      ]
    }
  ]
}

=== abgox/PSCompletions/completions/7z/language/zh-CN.json
{
  "meta": {
    "url": "https://7-zip.org/",
    "description": [
      "7-Zip 的命令行 cli 程序。"
    ]
  },
  "root": [
    {
      "name": "a",
      "tip": [
        "将文件添加到归档。",
        "E: a demo.zip demo\\   --- 将 demo 目录下的所有文件添加到 demo.zip 中"
      ]
    },
    {
      "name": "b",
      "tip": [
        "测试压缩或解压算法执行时的 CPU 占用。"
      ]
    },
    {
      "name": "d",
      "tip": [
        "从归档中删除文件。",
        "E: d demo.zip *.bak -r   --- 删除 demo.zip 中所有扩展名为 bak 的文件"
      ]
    },
    {
      "name": "e",
      "tip": [
        "将归档中的所有文件解压到指定路径。",
        "相比于 x, 所有文件将输出到同一个目录中。"
      ]
    },
    {
      "name": "h",
      "tip": [
        "计算文件的哈希值。"
      ]
    },
    {
      "name": "i",
      "tip": [
        "显示有关支持格式的信息。"
      ]
    },
    {
      "name": "l",
      "tip": [
        "列出归档的内容。"
      ]
    },
    {
      "name": "rn",
      "tip": [
        "重命名归档中的文件。"
      ]
    },
    {
      "name": "t",
      "tip": [
        "测试归档的完整性。"
      ]
    },
    {
      "name": "u",
      "tip": [
        "更新文件以归档。"
      ]
    },
    {
      "name": "x",
      "tip": [
        "提取文件。",
        "需要指定提取文件的完整路径。",
        "E: x D:\\demo.7z -oD:\\demo"
      ]
    }
  ],
  "option": [
    {
      "name": "--version",
      "alias": [
        "-v"
      ],
      "tip": [
        "显示当前版本。"
      ]
    }
  ],
  "common_option": [
    {
      "name": "--",
      "tip": [
        "停止开关和 @listfile 解析。"
      ]
    },
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "显示帮助信息。"
      ]
    },
    {
      "name": "-ai",
      "tip": [
        "包括归档。",
        "E: -ai!file1.txt    --- 包含 file1.txt",
        "   -air!file1.txt   --- 包含 file1.txt(包括子目录)",
        "   -ai!*.txt        --- 包含所有扩展名为 txt 的文件"
      ]
    },
    {
      "name": "-an",
      "tip": [
        "禁用 archive_name 字段。"
      ]
    },
    {
      "name": "-ao",
      "tip": [
        "设置覆盖模式。",
        "E: -aoa   --- 直接覆盖现有文件，而没有任何提示",
        "   -aos   --- 跳过现有文件，其不会被覆盖",
        "   -aot   --- 如果相同文件名的文件以存在，将自动重命名现有的文件",
        "   -aou   --- 如果相同文件名的文件以存在，将自动重命名被释放的文件"
      ]
    },
    {
      "name": "-ax",
      "tip": [
        "指定必须从操作中排除的归档。",
        "E: -ax!a*.7z   --- 排除所有扩展名为 7z 的归档"
      ]
    },
    {
      "name": "-bb",
      "tip": [
        "U: -bb[0|1|2|3]",
        "设置输出日志级别。"
      ]
    },
    {
      "name": "-bd",
      "tip": [
        "禁用进度指示器。"
      ]
    },
    {
      "name": "-bs",
      "tip": [
        "U: -bs[o|e|p]",
        "设置 output/error/progress 输出流。"
      ]
    },
    {
      "name": "-bt",
      "tip": [
        "显示执行时间统计信息。"
      ]
    },
    {
      "name": "-i",
      "tip": [
        "包含文件名。",
        "E: -i!*.txt   --- 包含所有扩展名为 txt 的文件"
      ]
    },
    {
      "name": "-m",
      "tip": [
        "设置压缩方法。"
      ]
    },
    {
      "name": "-mmt",
      "tip": [
        "设置 CPU 线程数。"
      ]
    },
    {
      "name": "-mx",
      "tip": [
        "设置压缩级别。"
      ]
    },
    {
      "name": "-o",
      "tip": [
        "设置输出目录。",
        "U: -oD:\\demo"
      ]
    },
    {
      "name": "-p",
      "tip": [
        "设置密码。",
        "E: -p123456   --- 设置密码为 123456"
      ]
    },
    {
      "name": "-r",
      "tip": [
        "递归子目录(e/l/t/x，默认开启)。",
        "E: -r-   --- 关闭递归子目录(a/d/u 等需要扫描磁盘文件的命令，默认使用它)",
        "   -r0   --- 开启递归子目录。但只应用于通配符。"
      ]
    },
    {
      "name": "-sa",
      "tip": [
        "U: -sa[a|e|s]",
        "设置归档名称模式。"
      ]
    },
    {
      "name": "-scc",
      "tip": [
        "U: -scc[UTF-8|WIN|DOS]",
        "设置控制台输入/输出字符集。"
      ]
    },
    {
      "name": "-scrc",
      "tip": [
        "为 x、e、h 命令设置哈希函数。"
      ]
    },
    {
      "name": "-scs",
      "tip": [
        "设置列表文件字符集。"
      ]
    },
    {
      "name": "-sdel",
      "tip": [
        "压缩后删除文件。"
      ]
    },
    {
      "name": "-seml",
      "tip": [
        "通过电子邮件发送归档。"
      ]
    },
    {
      "name": "-sfx",
      "tip": [
        "创建 SFX 归档。"
      ]
    },
    {
      "name": "-si",
      "tip": [
        "从标准输入读取数据。"
      ]
    },
    {
      "name": "-slp",
      "tip": [
        "设置大页面模式。"
      ]
    },
    {
      "name": "-slt",
      "tip": [
        "显示 l(列表)命令的技术信息。"
      ]
    },
    {
      "name": "-snh",
      "tip": [
        "将硬链接存储为链接。"
      ]
    },
    {
      "name": "-sni",
      "tip": [
        "存储 NT 安全信息。"
      ]
    },
    {
      "name": "-snl",
      "tip": [
        "将符号链接存储为链接。"
      ]
    },
    {
      "name": "-sns",
      "tip": [
        "存储 NTFS 备用流。"
      ]
    },
    {
      "name": "-so",
      "tip": [
        "将数据写入标准输出。"
      ]
    },
    {
      "name": "-spd",
      "tip": [
        "禁用文件名的通配符匹配。"
      ]
    },
    {
      "name": "-spe",
      "tip": [
        "消除提取命令的根文件夹重复。"
      ]
    },
    {
      "name": "-spf",
      "tip": [
        "使用完全限定的文件路径。"
      ]
    },
    {
      "name": "-ssc",
      "tip": [
        "设置区分大小写模式。"
      ]
    },
    {
      "name": "-sse",
      "tip": [
        "如果无法打开某些输入文件，则停止创建归档。"
      ]
    },
    {
      "name": "-ssp",
      "tip": [
        "归档时不更改源文件的最后访问时间。"
      ]
    },
    {
      "name": "-ssw",
      "tip": [
        "压缩共享文件。"
      ]
    },
    {
      "name": "-stl",
      "tip": [
        "从最近修改的文件设置归档时间戳。"
      ]
    },
    {
      "name": "-stm",
      "tip": [
        "设置 CPU 线程关联掩码(十六进制数)。"
      ]
    },
    {
      "name": "-stx",
      "tip": [
        "排除归档类型。"
      ]
    },
    {
      "name": "-t",
      "tip": [
        "U: -t[7z|bzip2|gzip|swfc|tar|wim|xz|zip...]",
        "设置归档类型。",
        "E: -tzip   --- 设置归档类型为 zip"
      ]
    },
    {
      "name": "-u",
      "tip": [
        "U: -u<[-][p#][q#][r#][x#][y#][z#][!newArchiveName]>",
        "更新选项。"
      ]
    },
    {
      "name": "-v",
      "tip": [
        "创建卷。",
        "E: -v10m         --- 创建 10MB 的卷",
        "   -v10k -v15k   --- 创建 10KB 和 15KB 的卷"
      ]
    },
    {
      "name": "-w",
      "tip": [
        "分配工作目录。",
        "E: -wD:\\temp   --- 设置工作目录为 D:\\temp"
      ]
    },
    {
      "name": "-x",
      "tip": [
        "排除文件名。",
        "E: -x!*.txt   --- 排除所有扩展名为 txt 的文件"
      ]
    },
    {
      "name": "-y",
      "tip": [
        "假定所有查询都为 Yes。"
      ]
    }
  ]
}

=== abgox/PSCompletions/completions/vite/language/zh-CN.json
{
  "meta": {
    "url": "https://github.com/vitejs/vite",
    "description": [
      "Vite - 下一代前端工具链。"
    ]
  },
  "root": [
    {
      "name": "build",
      "tip": [
        "为生产环境构建。"
      ],
      "option": [
        {
          "name": "--app",
          "tip": [
            "等同于 `builder: {}`。"
          ]
        },
        {
          "name": "--assetsDir",
          "tip": [
            "U: --assetsDir <dir>",
            "outDir 下放置资源的目录。",
            "默认: assets"
          ],
          "next": 0
        },
        {
          "name": "--assetsInlineLimit",
          "tip": [
            "U: --assetsInlineLimit <number>",
            "静态资源 base64 内联阈值（字节）。",
            "默认: 4096"
          ],
          "next": 0
        },
        {
          "name": "--emptyOutDir",
          "tip": [
            "当 outDir 在 root 之外时强制清空 outDir。"
          ]
        },
        {
          "name": "--manifest",
          "tip": [
            "U: --manifest [name]",
            "生成构建清单 json。"
          ],
          "next": 0
        },
        {
          "name": "--minify",
          "tip": [
            "U: --minify [minifier]",
            "启用/禁用压缩，或指定要使用的压缩器。",
            "可选值: true, false, 'oxc', 'terser', 'esbuild'",
            "默认: oxc"
          ],
          "next": [
            {
              "name": "esbuild",
              "tip": [
                "使用 esbuild 压缩器。"
              ]
            },
            {
              "name": "false",
              "tip": [
                "禁用压缩。"
              ]
            },
            {
              "name": "oxc",
              "tip": [
                "使用 oxc 压缩器。"
              ]
            },
            {
              "name": "terser",
              "tip": [
                "使用 terser 压缩器。"
              ]
            },
            {
              "name": "true",
              "tip": [
                "启用压缩。"
              ]
            }
          ]
        },
        {
          "name": "--outDir",
          "tip": [
            "U: --outDir <dir>",
            "输出目录。",
            "默认: dist"
          ],
          "next": 0
        },
        {
          "name": "--sourcemap",
          "tip": [
            "U: --sourcemap [output]",
            "为构建输出源映射。",
            "可选值: true, false, 'inline', 'hidden'",
            "默认: false"
          ],
          "next": [
            {
              "name": "false",
              "tip": [
                "禁用源映射。"
              ]
            },
            {
              "name": "hidden",
              "tip": [
                "生成单独的源映射。"
              ]
            },
            {
              "name": "inline",
              "tip": [
                "内联源映射。"
              ]
            },
            {
              "name": "true",
              "tip": [
                "启用源映射。"
              ]
            }
          ]
        },
        {
          "name": "--ssr",
          "tip": [
            "U: --ssr [entry]",
            "为服务器端渲染构建指定入口。"
          ],
          "next": 0
        },
        {
          "name": "--ssrManifest",
          "tip": [
            "U: --ssrManifest [name]",
            "生成 SSR 清单 json。"
          ],
          "next": 0
        },
        {
          "name": "--target",
          "tip": [
            "U: --target <target>",
            "转译目标。",
            "默认: 'baseline-widely-available'"
          ],
          "next": 0
        },
        {
          "name": "--watch",
          "alias": [
            "-w"
          ],
          "tip": [
            "U: -w, --watch",
            "当模块在磁盘上更改时重新构建。"
          ]
        }
      ]
    },
    {
      "name": "optimize",
      "tip": [
        "预打包依赖（已弃用，会自动运行）。"
      ]
    },
    {
      "name": "preview",
      "tip": [
        "本地预览生产构建。"
      ],
      "option": [
        {
          "name": "--host",
          "tip": [
            "U: --host [host]",
            "指定主机名。"
          ],
          "next": 0
        },
        {
          "name": "--open",
          "tip": [
            "U: --open [path]",
            "启动时打开浏览器。"
          ],
          "next": 0
        },
        {
          "name": "--outDir",
          "tip": [
            "U: --outDir <dir>",
            "输出目录。",
            "默认: dist"
          ],
          "next": 0
        },
        {
          "name": "--port",
          "tip": [
            "U: --port <port>",
            "指定端口。"
          ],
          "next": 0
        },
        {
          "name": "--strictPort",
          "tip": [
            "如果指定的端口已被使用则退出。"
          ]
        }
      ]
    }
  ],
  "option": [
    {
      "name": "--base",
      "tip": [
        "U: --base <path>",
        "公共基础路径。",
        "默认: /"
      ],
      "next": 0
    },
    {
      "name": "--clearScreen",
      "tip": [
        "允许/禁用日志记录时清屏。"
      ]
    },
    {
      "name": "--config",
      "alias": [
        "-c"
      ],
      "tip": [
        "U: -c, --config <file>",
        "使用指定的配置文件。"
      ],
      "next": 0
    },
    {
      "name": "--configLoader",
      "tip": [
        "U: --configLoader <loader>",
        "使用 'bundle' 通过 Rolldown 打包配置，或 'runner'（实验性）实时处理，或 'native'（实验性）使用原生运行时加载。",
        "默认: bundle"
      ],
      "next": [
        {
          "name": "bundle",
          "tip": [
            "通过 Rolldown 打包配置。"
          ]
        },
        {
          "name": "native",
          "tip": [
            "使用原生运行时加载（实验性）。"
          ]
        },
        {
          "name": "runner",
          "tip": [
            "实时处理配置（实验性）。"
          ]
        }
      ]
    },
    {
      "name": "--cors",
      "tip": [
        "启用 CORS。"
      ]
    },
    {
      "name": "--debug",
      "alias": [
        "-d"
      ],
      "tip": [
        "U: -d, --debug [feat]",
        "显示调试日志。"
      ],
      "next": 0
    },
    {
      "name": "--filter",
      "alias": [
        "-f"
      ],
      "tip": [
        "U: -f, --filter <filter>",
        "过滤调试日志。"
      ],
      "next": 0
    },
    {
      "name": "--force",
      "tip": [
        "强制优化器忽略缓存并重新打包。"
      ]
    },
    {
      "name": "--host",
      "tip": [
        "U: --host [host]",
        "指定主机名。"
      ],
      "next": 0
    },
    {
      "name": "--logLevel",
      "alias": [
        "-l"
      ],
      "tip": [
        "U: -l, --logLevel <level>",
        "日志级别。",
        "可选值: info, warn, error, silent"
      ],
      "next": [
        {
          "name": "error",
          "tip": [
            "错误级别日志。"
          ]
        },
        {
          "name": "info",
          "tip": [
            "信息级别日志。"
          ]
        },
        {
          "name": "silent",
          "tip": [
            "静默日志。"
          ]
        },
        {
          "name": "warn",
          "tip": [
            "警告级别日志。"
          ]
        }
      ]
    },
    {
      "name": "--mode",
      "alias": [
        "-m"
      ],
      "tip": [
        "U: -m, --mode <mode>",
        "设置环境模式。"
      ],
      "next": 0
    },
    {
      "name": "--open",
      "tip": [
        "U: --open [path]",
        "启动时打开浏览器。"
      ],
      "next": 0
    },
    {
      "name": "--port",
      "tip": [
        "U: --port <port>",
        "指定端口。"
      ],
      "next": 0
    },
    {
      "name": "--strictPort",
      "tip": [
        "如果指定的端口已被使用则退出。"
      ]
    },
    {
      "name": "--version",
      "alias": [
        "-v"
      ],
      "tip": [
        "U: -v, --version",
        "显示版本号。"
      ]
    }
  ],
  "common_option": [
    {
      "name": "--config",
      "alias": [
        "-c"
      ],
      "tip": [
        "U: -c, --config <file>",
        "使用指定的配置文件。"
      ],
      "next": 0
    },
    {
      "name": "--help",
      "alias": [
        "-h"
      ],
      "tip": [
        "U: -h, --help",
        "显示此消息。"
      ]
    },
    {
      "name": "--mode",
      "alias": [
        "-m"
      ],
      "tip": [
        "U: -m, --mode <mode>",
        "设置环境模式。"
      ],
      "next": 0
    }
  ]
}
